// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gophercourier/auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Email       string                 `protobuf:"bytes,1,opt,name=email,proto3"`
	xxx_hidden_Password    string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	xxx_hidden_Name        string                 `protobuf:"bytes,3,opt,name=name,proto3"`
	xxx_hidden_ClientId    string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3"`
	xxx_hidden_InviteToken string                 `protobuf:"bytes,5,opt,name=invite_token,json=inviteToken,proto3"`
	xxx_hidden_Locale      string                 `protobuf:"bytes,6,opt,name=locale,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.xxx_hidden_Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *RegisterRequest) GetClientId() string {
	if x != nil {
		return x.xxx_hidden_ClientId
	}
	return ""
}

func (x *RegisterRequest) GetInviteToken() string {
	if x != nil {
		return x.xxx_hidden_InviteToken
	}
	return ""
}

func (x *RegisterRequest) GetLocale() string {
	if x != nil {
		return x.xxx_hidden_Locale
	}
	return ""
}

func (x *RegisterRequest) SetEmail(v string) {
	x.xxx_hidden_Email = v
}

func (x *RegisterRequest) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

func (x *RegisterRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *RegisterRequest) SetClientId(v string) {
	x.xxx_hidden_ClientId = v
}

func (x *RegisterRequest) SetInviteToken(v string) {
	x.xxx_hidden_InviteToken = v
}

func (x *RegisterRequest) SetLocale(v string) {
	x.xxx_hidden_Locale = v
}

type RegisterRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Email    string
	Password string
	Name     string
	ClientId string
	// Optional invite token. Empty for self-serve registration.
	InviteToken string
	// Optional UI locale ("ru" | "en"). Drives single-language emails; empty
	// falls back to the bilingual template.
	Locale string
}

func (b0 RegisterRequest_builder) Build() *RegisterRequest {
	m0 := &RegisterRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Email = b.Email
	x.xxx_hidden_Password = b.Password
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_ClientId = b.ClientId
	x.xxx_hidden_InviteToken = b.InviteToken
	x.xxx_hidden_Locale = b.Locale
	return m0
}

type LoginRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Email    string                 `protobuf:"bytes,1,opt,name=email,proto3"`
	xxx_hidden_Password string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	xxx_hidden_ClientId string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.xxx_hidden_Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *LoginRequest) GetClientId() string {
	if x != nil {
		return x.xxx_hidden_ClientId
	}
	return ""
}

func (x *LoginRequest) SetEmail(v string) {
	x.xxx_hidden_Email = v
}

func (x *LoginRequest) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

func (x *LoginRequest) SetClientId(v string) {
	x.xxx_hidden_ClientId = v
}

type LoginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Email    string
	Password string
	ClientId string
}

func (b0 LoginRequest_builder) Build() *LoginRequest {
	m0 := &LoginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Email = b.Email
	x.xxx_hidden_Password = b.Password
	x.xxx_hidden_ClientId = b.ClientId
	return m0
}

type RefreshRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefreshToken string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3"`
	xxx_hidden_ClientId     string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.xxx_hidden_RefreshToken
	}
	return ""
}

func (x *RefreshRequest) GetClientId() string {
	if x != nil {
		return x.xxx_hidden_ClientId
	}
	return ""
}

func (x *RefreshRequest) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = v
}

func (x *RefreshRequest) SetClientId(v string) {
	x.xxx_hidden_ClientId = v
}

type RefreshRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefreshToken string
	ClientId     string
}

func (b0 RefreshRequest_builder) Build() *RefreshRequest {
	m0 := &RefreshRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefreshToken = b.RefreshToken
	x.xxx_hidden_ClientId = b.ClientId
	return m0
}

type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetMeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetMeRequest_builder) Build() *GetMeRequest {
	m0 := &GetMeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type RegisterResponse struct {
	state                                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AccessToken               string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3"`
	xxx_hidden_RefreshToken              string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3"`
	xxx_hidden_User                      *User                  `protobuf:"bytes,3,opt,name=user,proto3"`
	xxx_hidden_ActiveOrgId               string                 `protobuf:"bytes,10,opt,name=active_org_id,json=activeOrgId,proto3"`
	xxx_hidden_ActiveRoleId              string                 `protobuf:"bytes,11,opt,name=active_role_id,json=activeRoleId,proto3"`
	xxx_hidden_IsPlatformStaff           bool                   `protobuf:"varint,12,opt,name=is_platform_staff,json=isPlatformStaff,proto3"`
	xxx_hidden_Memberships               *[]*Membership         `protobuf:"bytes,13,rep,name=memberships,proto3"`
	xxx_hidden_RequiresEmailVerification bool                   `protobuf:"varint,14,opt,name=requires_email_verification,json=requiresEmailVerification,proto3"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterResponse) GetAccessToken() string {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return ""
}

func (x *RegisterResponse) GetRefreshToken() string {
	if x != nil {
		return x.xxx_hidden_RefreshToken
	}
	return ""
}

func (x *RegisterResponse) GetUser() *User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *RegisterResponse) GetActiveOrgId() string {
	if x != nil {
		return x.xxx_hidden_ActiveOrgId
	}
	return ""
}

func (x *RegisterResponse) GetActiveRoleId() string {
	if x != nil {
		return x.xxx_hidden_ActiveRoleId
	}
	return ""
}

func (x *RegisterResponse) GetIsPlatformStaff() bool {
	if x != nil {
		return x.xxx_hidden_IsPlatformStaff
	}
	return false
}

func (x *RegisterResponse) GetMemberships() []*Membership {
	if x != nil {
		if x.xxx_hidden_Memberships != nil {
			return *x.xxx_hidden_Memberships
		}
	}
	return nil
}

func (x *RegisterResponse) GetRequiresEmailVerification() bool {
	if x != nil {
		return x.xxx_hidden_RequiresEmailVerification
	}
	return false
}

func (x *RegisterResponse) SetAccessToken(v string) {
	x.xxx_hidden_AccessToken = v
}

func (x *RegisterResponse) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = v
}

func (x *RegisterResponse) SetUser(v *User) {
	x.xxx_hidden_User = v
}

func (x *RegisterResponse) SetActiveOrgId(v string) {
	x.xxx_hidden_ActiveOrgId = v
}

func (x *RegisterResponse) SetActiveRoleId(v string) {
	x.xxx_hidden_ActiveRoleId = v
}

func (x *RegisterResponse) SetIsPlatformStaff(v bool) {
	x.xxx_hidden_IsPlatformStaff = v
}

func (x *RegisterResponse) SetMemberships(v []*Membership) {
	x.xxx_hidden_Memberships = &v
}

func (x *RegisterResponse) SetRequiresEmailVerification(v bool) {
	x.xxx_hidden_RequiresEmailVerification = v
}

func (x *RegisterResponse) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *RegisterResponse) ClearUser() {
	x.xxx_hidden_User = nil
}

type RegisterResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AccessToken               string
	RefreshToken              string
	User                      *User
	ActiveOrgId               string
	ActiveRoleId              string
	IsPlatformStaff           bool
	Memberships               []*Membership
	RequiresEmailVerification bool
}

func (b0 RegisterResponse_builder) Build() *RegisterResponse {
	m0 := &RegisterResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AccessToken = b.AccessToken
	x.xxx_hidden_RefreshToken = b.RefreshToken
	x.xxx_hidden_User = b.User
	x.xxx_hidden_ActiveOrgId = b.ActiveOrgId
	x.xxx_hidden_ActiveRoleId = b.ActiveRoleId
	x.xxx_hidden_IsPlatformStaff = b.IsPlatformStaff
	x.xxx_hidden_Memberships = &b.Memberships
	x.xxx_hidden_RequiresEmailVerification = b.RequiresEmailVerification
	return m0
}

type LoginResponse struct {
	state                                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AccessToken               string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3"`
	xxx_hidden_RefreshToken              string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3"`
	xxx_hidden_User                      *User                  `protobuf:"bytes,3,opt,name=user,proto3"`
	xxx_hidden_ActiveOrgId               string                 `protobuf:"bytes,10,opt,name=active_org_id,json=activeOrgId,proto3"`
	xxx_hidden_ActiveRoleId              string                 `protobuf:"bytes,11,opt,name=active_role_id,json=activeRoleId,proto3"`
	xxx_hidden_IsPlatformStaff           bool                   `protobuf:"varint,12,opt,name=is_platform_staff,json=isPlatformStaff,proto3"`
	xxx_hidden_Memberships               *[]*Membership         `protobuf:"bytes,13,rep,name=memberships,proto3"`
	xxx_hidden_RequiresEmailVerification bool                   `protobuf:"varint,14,opt,name=requires_email_verification,json=requiresEmailVerification,proto3"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.xxx_hidden_RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *LoginResponse) GetActiveOrgId() string {
	if x != nil {
		return x.xxx_hidden_ActiveOrgId
	}
	return ""
}

func (x *LoginResponse) GetActiveRoleId() string {
	if x != nil {
		return x.xxx_hidden_ActiveRoleId
	}
	return ""
}

func (x *LoginResponse) GetIsPlatformStaff() bool {
	if x != nil {
		return x.xxx_hidden_IsPlatformStaff
	}
	return false
}

func (x *LoginResponse) GetMemberships() []*Membership {
	if x != nil {
		if x.xxx_hidden_Memberships != nil {
			return *x.xxx_hidden_Memberships
		}
	}
	return nil
}

func (x *LoginResponse) GetRequiresEmailVerification() bool {
	if x != nil {
		return x.xxx_hidden_RequiresEmailVerification
	}
	return false
}

func (x *LoginResponse) SetAccessToken(v string) {
	x.xxx_hidden_AccessToken = v
}

func (x *LoginResponse) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = v
}

func (x *LoginResponse) SetUser(v *User) {
	x.xxx_hidden_User = v
}

func (x *LoginResponse) SetActiveOrgId(v string) {
	x.xxx_hidden_ActiveOrgId = v
}

func (x *LoginResponse) SetActiveRoleId(v string) {
	x.xxx_hidden_ActiveRoleId = v
}

func (x *LoginResponse) SetIsPlatformStaff(v bool) {
	x.xxx_hidden_IsPlatformStaff = v
}

func (x *LoginResponse) SetMemberships(v []*Membership) {
	x.xxx_hidden_Memberships = &v
}

func (x *LoginResponse) SetRequiresEmailVerification(v bool) {
	x.xxx_hidden_RequiresEmailVerification = v
}

func (x *LoginResponse) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *LoginResponse) ClearUser() {
	x.xxx_hidden_User = nil
}

type LoginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AccessToken               string
	RefreshToken              string
	User                      *User
	ActiveOrgId               string
	ActiveRoleId              string
	IsPlatformStaff           bool
	Memberships               []*Membership
	RequiresEmailVerification bool
}

func (b0 LoginResponse_builder) Build() *LoginResponse {
	m0 := &LoginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AccessToken = b.AccessToken
	x.xxx_hidden_RefreshToken = b.RefreshToken
	x.xxx_hidden_User = b.User
	x.xxx_hidden_ActiveOrgId = b.ActiveOrgId
	x.xxx_hidden_ActiveRoleId = b.ActiveRoleId
	x.xxx_hidden_IsPlatformStaff = b.IsPlatformStaff
	x.xxx_hidden_Memberships = &b.Memberships
	x.xxx_hidden_RequiresEmailVerification = b.RequiresEmailVerification
	return m0
}

type RefreshResponse struct {
	state                                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AccessToken               string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3"`
	xxx_hidden_RefreshToken              string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3"`
	xxx_hidden_User                      *User                  `protobuf:"bytes,3,opt,name=user,proto3"`
	xxx_hidden_ActiveOrgId               string                 `protobuf:"bytes,10,opt,name=active_org_id,json=activeOrgId,proto3"`
	xxx_hidden_ActiveRoleId              string                 `protobuf:"bytes,11,opt,name=active_role_id,json=activeRoleId,proto3"`
	xxx_hidden_IsPlatformStaff           bool                   `protobuf:"varint,12,opt,name=is_platform_staff,json=isPlatformStaff,proto3"`
	xxx_hidden_Memberships               *[]*Membership         `protobuf:"bytes,13,rep,name=memberships,proto3"`
	xxx_hidden_RequiresEmailVerification bool                   `protobuf:"varint,14,opt,name=requires_email_verification,json=requiresEmailVerification,proto3"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RefreshResponse) GetAccessToken() string {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return ""
}

func (x *RefreshResponse) GetRefreshToken() string {
	if x != nil {
		return x.xxx_hidden_RefreshToken
	}
	return ""
}

func (x *RefreshResponse) GetUser() *User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *RefreshResponse) GetActiveOrgId() string {
	if x != nil {
		return x.xxx_hidden_ActiveOrgId
	}
	return ""
}

func (x *RefreshResponse) GetActiveRoleId() string {
	if x != nil {
		return x.xxx_hidden_ActiveRoleId
	}
	return ""
}

func (x *RefreshResponse) GetIsPlatformStaff() bool {
	if x != nil {
		return x.xxx_hidden_IsPlatformStaff
	}
	return false
}

func (x *RefreshResponse) GetMemberships() []*Membership {
	if x != nil {
		if x.xxx_hidden_Memberships != nil {
			return *x.xxx_hidden_Memberships
		}
	}
	return nil
}

func (x *RefreshResponse) GetRequiresEmailVerification() bool {
	if x != nil {
		return x.xxx_hidden_RequiresEmailVerification
	}
	return false
}

func (x *RefreshResponse) SetAccessToken(v string) {
	x.xxx_hidden_AccessToken = v
}

func (x *RefreshResponse) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = v
}

func (x *RefreshResponse) SetUser(v *User) {
	x.xxx_hidden_User = v
}

func (x *RefreshResponse) SetActiveOrgId(v string) {
	x.xxx_hidden_ActiveOrgId = v
}

func (x *RefreshResponse) SetActiveRoleId(v string) {
	x.xxx_hidden_ActiveRoleId = v
}

func (x *RefreshResponse) SetIsPlatformStaff(v bool) {
	x.xxx_hidden_IsPlatformStaff = v
}

func (x *RefreshResponse) SetMemberships(v []*Membership) {
	x.xxx_hidden_Memberships = &v
}

func (x *RefreshResponse) SetRequiresEmailVerification(v bool) {
	x.xxx_hidden_RequiresEmailVerification = v
}

func (x *RefreshResponse) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *RefreshResponse) ClearUser() {
	x.xxx_hidden_User = nil
}

type RefreshResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AccessToken               string
	RefreshToken              string
	User                      *User
	ActiveOrgId               string
	ActiveRoleId              string
	IsPlatformStaff           bool
	Memberships               []*Membership
	RequiresEmailVerification bool
}

func (b0 RefreshResponse_builder) Build() *RefreshResponse {
	m0 := &RefreshResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AccessToken = b.AccessToken
	x.xxx_hidden_RefreshToken = b.RefreshToken
	x.xxx_hidden_User = b.User
	x.xxx_hidden_ActiveOrgId = b.ActiveOrgId
	x.xxx_hidden_ActiveRoleId = b.ActiveRoleId
	x.xxx_hidden_IsPlatformStaff = b.IsPlatformStaff
	x.xxx_hidden_Memberships = &b.Memberships
	x.xxx_hidden_RequiresEmailVerification = b.RequiresEmailVerification
	return m0
}

type GetMeResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_User *User                  `protobuf:"bytes,1,opt,name=user,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetMeResponse) GetUser() *User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *GetMeResponse) SetUser(v *User) {
	x.xxx_hidden_User = v
}

func (x *GetMeResponse) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *GetMeResponse) ClearUser() {
	x.xxx_hidden_User = nil
}

type GetMeResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	User *User
}

func (b0 GetMeResponse_builder) Build() *GetMeResponse {
	m0 := &GetMeResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_User = b.User
	return m0
}

// User is the public projection of the user entity.
type User struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id              string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Email           string                 `protobuf:"bytes,2,opt,name=email,proto3"`
	xxx_hidden_Name            string                 `protobuf:"bytes,3,opt,name=name,proto3"`
	xxx_hidden_CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_EmailVerified   bool                   `protobuf:"varint,5,opt,name=email_verified,json=emailVerified,proto3"`
	xxx_hidden_IsPlatformStaff bool                   `protobuf:"varint,6,opt,name=is_platform_staff,json=isPlatformStaff,proto3"`
	xxx_hidden_LastActiveOrgId string                 `protobuf:"bytes,7,opt,name=last_active_org_id,json=lastActiveOrgId,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *User) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.xxx_hidden_Email
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *User) GetEmailVerified() bool {
	if x != nil {
		return x.xxx_hidden_EmailVerified
	}
	return false
}

func (x *User) GetIsPlatformStaff() bool {
	if x != nil {
		return x.xxx_hidden_IsPlatformStaff
	}
	return false
}

func (x *User) GetLastActiveOrgId() string {
	if x != nil {
		return x.xxx_hidden_LastActiveOrgId
	}
	return ""
}

func (x *User) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *User) SetEmail(v string) {
	x.xxx_hidden_Email = v
}

func (x *User) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *User) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *User) SetEmailVerified(v bool) {
	x.xxx_hidden_EmailVerified = v
}

func (x *User) SetIsPlatformStaff(v bool) {
	x.xxx_hidden_IsPlatformStaff = v
}

func (x *User) SetLastActiveOrgId(v string) {
	x.xxx_hidden_LastActiveOrgId = v
}

func (x *User) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *User) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

type User_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id              string
	Email           string
	Name            string
	CreatedAt       *timestamppb.Timestamp
	EmailVerified   bool
	IsPlatformStaff bool
	LastActiveOrgId string
}

func (b0 User_builder) Build() *User {
	m0 := &User{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Email = b.Email
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_EmailVerified = b.EmailVerified
	x.xxx_hidden_IsPlatformStaff = b.IsPlatformStaff
	x.xxx_hidden_LastActiveOrgId = b.LastActiveOrgId
	return m0
}

// Membership is the denormalized projection used in /login, /me, /my_orgs.
type Membership struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId      string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	xxx_hidden_OrgName    string                 `protobuf:"bytes,2,opt,name=org_name,json=orgName,proto3"`
	xxx_hidden_OrgSlug    string                 `protobuf:"bytes,3,opt,name=org_slug,json=orgSlug,proto3"`
	xxx_hidden_IsPersonal bool                   `protobuf:"varint,4,opt,name=is_personal,json=isPersonal,proto3"`
	xxx_hidden_RoleId     string                 `protobuf:"bytes,5,opt,name=role_id,json=roleId,proto3"`
	xxx_hidden_RoleName   string                 `protobuf:"bytes,6,opt,name=role_name,json=roleName,proto3"`
	xxx_hidden_JoinedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=joined_at,json=joinedAt,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Membership) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *Membership) GetOrgName() string {
	if x != nil {
		return x.xxx_hidden_OrgName
	}
	return ""
}

func (x *Membership) GetOrgSlug() string {
	if x != nil {
		return x.xxx_hidden_OrgSlug
	}
	return ""
}

func (x *Membership) GetIsPersonal() bool {
	if x != nil {
		return x.xxx_hidden_IsPersonal
	}
	return false
}

func (x *Membership) GetRoleId() string {
	if x != nil {
		return x.xxx_hidden_RoleId
	}
	return ""
}

func (x *Membership) GetRoleName() string {
	if x != nil {
		return x.xxx_hidden_RoleName
	}
	return ""
}

func (x *Membership) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_JoinedAt
	}
	return nil
}

func (x *Membership) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

func (x *Membership) SetOrgName(v string) {
	x.xxx_hidden_OrgName = v
}

func (x *Membership) SetOrgSlug(v string) {
	x.xxx_hidden_OrgSlug = v
}

func (x *Membership) SetIsPersonal(v bool) {
	x.xxx_hidden_IsPersonal = v
}

func (x *Membership) SetRoleId(v string) {
	x.xxx_hidden_RoleId = v
}

func (x *Membership) SetRoleName(v string) {
	x.xxx_hidden_RoleName = v
}

func (x *Membership) SetJoinedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_JoinedAt = v
}

func (x *Membership) HasJoinedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_JoinedAt != nil
}

func (x *Membership) ClearJoinedAt() {
	x.xxx_hidden_JoinedAt = nil
}

type Membership_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OrgId      string
	OrgName    string
	OrgSlug    string
	IsPersonal bool
	RoleId     string
	RoleName   string
	JoinedAt   *timestamppb.Timestamp
}

func (b0 Membership_builder) Build() *Membership {
	m0 := &Membership{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	x.xxx_hidden_OrgName = b.OrgName
	x.xxx_hidden_OrgSlug = b.OrgSlug
	x.xxx_hidden_IsPersonal = b.IsPersonal
	x.xxx_hidden_RoleId = b.RoleId
	x.xxx_hidden_RoleName = b.RoleName
	x.xxx_hidden_JoinedAt = b.JoinedAt
	return m0
}

// SwitchOrgRequest changes the active org context for the calling session.
type SwitchOrgRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SwitchOrgRequest) Reset() {
	*x = SwitchOrgRequest{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchOrgRequest) ProtoMessage() {}

func (x *SwitchOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SwitchOrgRequest) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *SwitchOrgRequest) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

type SwitchOrgRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OrgId string
}

func (b0 SwitchOrgRequest_builder) Build() *SwitchOrgRequest {
	m0 := &SwitchOrgRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	return m0
}

type SwitchOrgResponse struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AccessToken     string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3"`
	xxx_hidden_RefreshToken    string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3"`
	xxx_hidden_User            *User                  `protobuf:"bytes,3,opt,name=user,proto3"`
	xxx_hidden_ActiveOrgId     string                 `protobuf:"bytes,10,opt,name=active_org_id,json=activeOrgId,proto3"`
	xxx_hidden_ActiveRoleId    string                 `protobuf:"bytes,11,opt,name=active_role_id,json=activeRoleId,proto3"`
	xxx_hidden_IsPlatformStaff bool                   `protobuf:"varint,12,opt,name=is_platform_staff,json=isPlatformStaff,proto3"`
	xxx_hidden_Memberships     *[]*Membership         `protobuf:"bytes,13,rep,name=memberships,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *SwitchOrgResponse) Reset() {
	*x = SwitchOrgResponse{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchOrgResponse) ProtoMessage() {}

func (x *SwitchOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SwitchOrgResponse) GetAccessToken() string {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return ""
}

func (x *SwitchOrgResponse) GetRefreshToken() string {
	if x != nil {
		return x.xxx_hidden_RefreshToken
	}
	return ""
}

func (x *SwitchOrgResponse) GetUser() *User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *SwitchOrgResponse) GetActiveOrgId() string {
	if x != nil {
		return x.xxx_hidden_ActiveOrgId
	}
	return ""
}

func (x *SwitchOrgResponse) GetActiveRoleId() string {
	if x != nil {
		return x.xxx_hidden_ActiveRoleId
	}
	return ""
}

func (x *SwitchOrgResponse) GetIsPlatformStaff() bool {
	if x != nil {
		return x.xxx_hidden_IsPlatformStaff
	}
	return false
}

func (x *SwitchOrgResponse) GetMemberships() []*Membership {
	if x != nil {
		if x.xxx_hidden_Memberships != nil {
			return *x.xxx_hidden_Memberships
		}
	}
	return nil
}

func (x *SwitchOrgResponse) SetAccessToken(v string) {
	x.xxx_hidden_AccessToken = v
}

func (x *SwitchOrgResponse) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = v
}

func (x *SwitchOrgResponse) SetUser(v *User) {
	x.xxx_hidden_User = v
}

func (x *SwitchOrgResponse) SetActiveOrgId(v string) {
	x.xxx_hidden_ActiveOrgId = v
}

func (x *SwitchOrgResponse) SetActiveRoleId(v string) {
	x.xxx_hidden_ActiveRoleId = v
}

func (x *SwitchOrgResponse) SetIsPlatformStaff(v bool) {
	x.xxx_hidden_IsPlatformStaff = v
}

func (x *SwitchOrgResponse) SetMemberships(v []*Membership) {
	x.xxx_hidden_Memberships = &v
}

func (x *SwitchOrgResponse) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *SwitchOrgResponse) ClearUser() {
	x.xxx_hidden_User = nil
}

type SwitchOrgResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AccessToken string
	// refresh_token is empty — switch_org does not rotate refresh.
	RefreshToken    string
	User            *User
	ActiveOrgId     string
	ActiveRoleId    string
	IsPlatformStaff bool
	Memberships     []*Membership
}

func (b0 SwitchOrgResponse_builder) Build() *SwitchOrgResponse {
	m0 := &SwitchOrgResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AccessToken = b.AccessToken
	x.xxx_hidden_RefreshToken = b.RefreshToken
	x.xxx_hidden_User = b.User
	x.xxx_hidden_ActiveOrgId = b.ActiveOrgId
	x.xxx_hidden_ActiveRoleId = b.ActiveRoleId
	x.xxx_hidden_IsPlatformStaff = b.IsPlatformStaff
	x.xxx_hidden_Memberships = &b.Memberships
	return m0
}

type MeRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeRequest) Reset() {
	*x = MeRequest{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeRequest) ProtoMessage() {}

func (x *MeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type MeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 MeRequest_builder) Build() *MeRequest {
	m0 := &MeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type MeResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_User        *User                  `protobuf:"bytes,1,opt,name=user,proto3"`
	xxx_hidden_ActiveOrg   *ActiveOrg             `protobuf:"bytes,2,opt,name=active_org,json=activeOrg,proto3"`
	xxx_hidden_Memberships *[]*Membership         `protobuf:"bytes,3,rep,name=memberships,proto3"`
	xxx_hidden_Sessions    *[]*SessionView        `protobuf:"bytes,4,rep,name=sessions,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MeResponse) Reset() {
	*x = MeResponse{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeResponse) ProtoMessage() {}

func (x *MeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MeResponse) GetUser() *User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *MeResponse) GetActiveOrg() *ActiveOrg {
	if x != nil {
		return x.xxx_hidden_ActiveOrg
	}
	return nil
}

func (x *MeResponse) GetMemberships() []*Membership {
	if x != nil {
		if x.xxx_hidden_Memberships != nil {
			return *x.xxx_hidden_Memberships
		}
	}
	return nil
}

func (x *MeResponse) GetSessions() []*SessionView {
	if x != nil {
		if x.xxx_hidden_Sessions != nil {
			return *x.xxx_hidden_Sessions
		}
	}
	return nil
}

func (x *MeResponse) SetUser(v *User) {
	x.xxx_hidden_User = v
}

func (x *MeResponse) SetActiveOrg(v *ActiveOrg) {
	x.xxx_hidden_ActiveOrg = v
}

func (x *MeResponse) SetMemberships(v []*Membership) {
	x.xxx_hidden_Memberships = &v
}

func (x *MeResponse) SetSessions(v []*SessionView) {
	x.xxx_hidden_Sessions = &v
}

func (x *MeResponse) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *MeResponse) HasActiveOrg() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ActiveOrg != nil
}

func (x *MeResponse) ClearUser() {
	x.xxx_hidden_User = nil
}

func (x *MeResponse) ClearActiveOrg() {
	x.xxx_hidden_ActiveOrg = nil
}

type MeResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	User        *User
	ActiveOrg   *ActiveOrg
	Memberships []*Membership
	Sessions    []*SessionView
}

func (b0 MeResponse_builder) Build() *MeResponse {
	m0 := &MeResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_User = b.User
	x.xxx_hidden_ActiveOrg = b.ActiveOrg
	x.xxx_hidden_Memberships = &b.Memberships
	x.xxx_hidden_Sessions = &b.Sessions
	return m0
}

type ActiveOrg struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId      string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	xxx_hidden_OrgName    string                 `protobuf:"bytes,2,opt,name=org_name,json=orgName,proto3"`
	xxx_hidden_OrgSlug    string                 `protobuf:"bytes,3,opt,name=org_slug,json=orgSlug,proto3"`
	xxx_hidden_IsPersonal bool                   `protobuf:"varint,4,opt,name=is_personal,json=isPersonal,proto3"`
	xxx_hidden_RoleId     string                 `protobuf:"bytes,5,opt,name=role_id,json=roleId,proto3"`
	xxx_hidden_RoleName   string                 `protobuf:"bytes,6,opt,name=role_name,json=roleName,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ActiveOrg) Reset() {
	*x = ActiveOrg{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveOrg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveOrg) ProtoMessage() {}

func (x *ActiveOrg) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ActiveOrg) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *ActiveOrg) GetOrgName() string {
	if x != nil {
		return x.xxx_hidden_OrgName
	}
	return ""
}

func (x *ActiveOrg) GetOrgSlug() string {
	if x != nil {
		return x.xxx_hidden_OrgSlug
	}
	return ""
}

func (x *ActiveOrg) GetIsPersonal() bool {
	if x != nil {
		return x.xxx_hidden_IsPersonal
	}
	return false
}

func (x *ActiveOrg) GetRoleId() string {
	if x != nil {
		return x.xxx_hidden_RoleId
	}
	return ""
}

func (x *ActiveOrg) GetRoleName() string {
	if x != nil {
		return x.xxx_hidden_RoleName
	}
	return ""
}

func (x *ActiveOrg) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

func (x *ActiveOrg) SetOrgName(v string) {
	x.xxx_hidden_OrgName = v
}

func (x *ActiveOrg) SetOrgSlug(v string) {
	x.xxx_hidden_OrgSlug = v
}

func (x *ActiveOrg) SetIsPersonal(v bool) {
	x.xxx_hidden_IsPersonal = v
}

func (x *ActiveOrg) SetRoleId(v string) {
	x.xxx_hidden_RoleId = v
}

func (x *ActiveOrg) SetRoleName(v string) {
	x.xxx_hidden_RoleName = v
}

type ActiveOrg_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OrgId      string
	OrgName    string
	OrgSlug    string
	IsPersonal bool
	RoleId     string
	RoleName   string
}

func (b0 ActiveOrg_builder) Build() *ActiveOrg {
	m0 := &ActiveOrg{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	x.xxx_hidden_OrgName = b.OrgName
	x.xxx_hidden_OrgSlug = b.OrgSlug
	x.xxx_hidden_IsPersonal = b.IsPersonal
	x.xxx_hidden_RoleId = b.RoleId
	x.xxx_hidden_RoleName = b.RoleName
	return m0
}

type SessionView struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id         string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_ClientId   string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3"`
	xxx_hidden_UserAgent  string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3"`
	xxx_hidden_Ip         string                 `protobuf:"bytes,4,opt,name=ip,proto3"`
	xxx_hidden_LastUsedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_used_at,json=lastUsedAt,proto3"`
	xxx_hidden_IsCurrent  bool                   `protobuf:"varint,6,opt,name=is_current,json=isCurrent,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SessionView) Reset() {
	*x = SessionView{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionView) ProtoMessage() {}

func (x *SessionView) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SessionView) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *SessionView) GetClientId() string {
	if x != nil {
		return x.xxx_hidden_ClientId
	}
	return ""
}

func (x *SessionView) GetUserAgent() string {
	if x != nil {
		return x.xxx_hidden_UserAgent
	}
	return ""
}

func (x *SessionView) GetIp() string {
	if x != nil {
		return x.xxx_hidden_Ip
	}
	return ""
}

func (x *SessionView) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastUsedAt
	}
	return nil
}

func (x *SessionView) GetIsCurrent() bool {
	if x != nil {
		return x.xxx_hidden_IsCurrent
	}
	return false
}

func (x *SessionView) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *SessionView) SetClientId(v string) {
	x.xxx_hidden_ClientId = v
}

func (x *SessionView) SetUserAgent(v string) {
	x.xxx_hidden_UserAgent = v
}

func (x *SessionView) SetIp(v string) {
	x.xxx_hidden_Ip = v
}

func (x *SessionView) SetLastUsedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastUsedAt = v
}

func (x *SessionView) SetIsCurrent(v bool) {
	x.xxx_hidden_IsCurrent = v
}

func (x *SessionView) HasLastUsedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastUsedAt != nil
}

func (x *SessionView) ClearLastUsedAt() {
	x.xxx_hidden_LastUsedAt = nil
}

type SessionView_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id         string
	ClientId   string
	UserAgent  string
	Ip         string
	LastUsedAt *timestamppb.Timestamp
	IsCurrent  bool
}

func (b0 SessionView_builder) Build() *SessionView {
	m0 := &SessionView{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_ClientId = b.ClientId
	x.xxx_hidden_UserAgent = b.UserAgent
	x.xxx_hidden_Ip = b.Ip
	x.xxx_hidden_LastUsedAt = b.LastUsedAt
	x.xxx_hidden_IsCurrent = b.IsCurrent
	return m0
}

type MyOrgsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyOrgsRequest) Reset() {
	*x = MyOrgsRequest{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyOrgsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyOrgsRequest) ProtoMessage() {}

func (x *MyOrgsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type MyOrgsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 MyOrgsRequest_builder) Build() *MyOrgsRequest {
	m0 := &MyOrgsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type MyOrgsResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Memberships *[]*Membership         `protobuf:"bytes,1,rep,name=memberships,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MyOrgsResponse) Reset() {
	*x = MyOrgsResponse{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyOrgsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyOrgsResponse) ProtoMessage() {}

func (x *MyOrgsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MyOrgsResponse) GetMemberships() []*Membership {
	if x != nil {
		if x.xxx_hidden_Memberships != nil {
			return *x.xxx_hidden_Memberships
		}
	}
	return nil
}

func (x *MyOrgsResponse) SetMemberships(v []*Membership) {
	x.xxx_hidden_Memberships = &v
}

type MyOrgsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Memberships []*Membership
}

func (b0 MyOrgsResponse_builder) Build() *MyOrgsResponse {
	m0 := &MyOrgsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Memberships = &b.Memberships
	return m0
}

type VerifyEmailRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token string                 `protobuf:"bytes,1,opt,name=token,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifyEmailRequest) Reset() {
	*x = VerifyEmailRequest{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailRequest) ProtoMessage() {}

func (x *VerifyEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VerifyEmailRequest) GetToken() string {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return ""
}

func (x *VerifyEmailRequest) SetToken(v string) {
	x.xxx_hidden_Token = v
}

type VerifyEmailRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token string
}

func (b0 VerifyEmailRequest_builder) Build() *VerifyEmailRequest {
	m0 := &VerifyEmailRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Token = b.Token
	return m0
}

type VerifyEmailResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailResponse) Reset() {
	*x = VerifyEmailResponse{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailResponse) ProtoMessage() {}

func (x *VerifyEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type VerifyEmailResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 VerifyEmailResponse_builder) Build() *VerifyEmailResponse {
	m0 := &VerifyEmailResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ResendVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendVerificationRequest) Reset() {
	*x = ResendVerificationRequest{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendVerificationRequest) ProtoMessage() {}

func (x *ResendVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ResendVerificationRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ResendVerificationRequest_builder) Build() *ResendVerificationRequest {
	m0 := &ResendVerificationRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ResendVerificationResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendVerificationResponse) Reset() {
	*x = ResendVerificationResponse{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendVerificationResponse) ProtoMessage() {}

func (x *ResendVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ResendVerificationResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ResendVerificationResponse_builder) Build() *ResendVerificationResponse {
	m0 := &ResendVerificationResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ChangePasswordRequest struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OldPassword         string                 `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3"`
	xxx_hidden_NewPassword         string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3"`
	xxx_hidden_RevokeOtherSessions bool                   `protobuf:"varint,3,opt,name=revoke_other_sessions,json=revokeOtherSessions,proto3"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.xxx_hidden_OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.xxx_hidden_NewPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetRevokeOtherSessions() bool {
	if x != nil {
		return x.xxx_hidden_RevokeOtherSessions
	}
	return false
}

func (x *ChangePasswordRequest) SetOldPassword(v string) {
	x.xxx_hidden_OldPassword = v
}

func (x *ChangePasswordRequest) SetNewPassword(v string) {
	x.xxx_hidden_NewPassword = v
}

func (x *ChangePasswordRequest) SetRevokeOtherSessions(v bool) {
	x.xxx_hidden_RevokeOtherSessions = v
}

type ChangePasswordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OldPassword string
	NewPassword string
	// Reserved for future explicit control. Server currently always revokes other
	// sessions (proto3 default false would not match the secure default).
	RevokeOtherSessions bool
}

func (b0 ChangePasswordRequest_builder) Build() *ChangePasswordRequest {
	m0 := &ChangePasswordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OldPassword = b.OldPassword
	x.xxx_hidden_NewPassword = b.NewPassword
	x.xxx_hidden_RevokeOtherSessions = b.RevokeOtherSessions
	return m0
}

type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ChangePasswordResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ChangePasswordResponse_builder) Build() *ChangePasswordResponse {
	m0 := &ChangePasswordResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LogoutRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LogoutRequest_builder) Build() *LogoutRequest {
	m0 := &LogoutRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LogoutResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LogoutResponse_builder) Build() *LogoutResponse {
	m0 := &LogoutResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type RevokeSessionRequest struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RevokeSessionRequest) GetSessionId() string {
	if x != nil {
		return x.xxx_hidden_SessionId
	}
	return ""
}

func (x *RevokeSessionRequest) SetSessionId(v string) {
	x.xxx_hidden_SessionId = v
}

type RevokeSessionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SessionId string
}

func (b0 RevokeSessionRequest_builder) Build() *RevokeSessionRequest {
	m0 := &RevokeSessionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SessionId = b.SessionId
	return m0
}

type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RevokeSessionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RevokeSessionResponse_builder) Build() *RevokeSessionResponse {
	m0 := &RevokeSessionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type LogoutAllRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutAllRequest) Reset() {
	*x = LogoutAllRequest{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutAllRequest) ProtoMessage() {}

func (x *LogoutAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LogoutAllRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LogoutAllRequest_builder) Build() *LogoutAllRequest {
	m0 := &LogoutAllRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type LogoutAllResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RevokedCount int32                  `protobuf:"varint,1,opt,name=revoked_count,json=revokedCount,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LogoutAllResponse) Reset() {
	*x = LogoutAllResponse{}
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutAllResponse) ProtoMessage() {}

func (x *LogoutAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_auth_v1_auth_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LogoutAllResponse) GetRevokedCount() int32 {
	if x != nil {
		return x.xxx_hidden_RevokedCount
	}
	return 0
}

func (x *LogoutAllResponse) SetRevokedCount(v int32) {
	x.xxx_hidden_RevokedCount = v
}

type LogoutAllResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RevokedCount int32
}

func (b0 LogoutAllResponse_builder) Build() *LogoutAllResponse {
	m0 := &LogoutAllResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RevokedCount = b.RevokedCount
	return m0
}

var File_gophercourier_auth_v1_auth_proto protoreflect.FileDescriptor

const file_gophercourier_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	" gophercourier/auth/v1/auth.proto\x12\x15gophercourier.auth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12!\n" +
	"\finvite_token\x18\x05 \x01(\tR\vinviteToken\x12\x16\n" +
	"\x06locale\x18\x06 \x01(\tR\x06locale\"]\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\"R\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"\x0e\n" +
	"\fGetMeRequest\"\x86\x03\n" +
	"\x10RegisterResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12/\n" +
	"\x04user\x18\x03 \x01(\v2\x1b.gophercourier.auth.v1.UserR\x04user\x12\"\n" +
	"\ractive_org_id\x18\n" +
	" \x01(\tR\vactiveOrgId\x12$\n" +
	"\x0eactive_role_id\x18\v \x01(\tR\factiveRoleId\x12*\n" +
	"\x11is_platform_staff\x18\f \x01(\bR\x0fisPlatformStaff\x12C\n" +
	"\vmemberships\x18\r \x03(\v2!.gophercourier.auth.v1.MembershipR\vmemberships\x12>\n" +
	"\x1brequires_email_verification\x18\x0e \x01(\bR\x19requiresEmailVerification\"\x83\x03\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12/\n" +
	"\x04user\x18\x03 \x01(\v2\x1b.gophercourier.auth.v1.UserR\x04user\x12\"\n" +
	"\ractive_org_id\x18\n" +
	" \x01(\tR\vactiveOrgId\x12$\n" +
	"\x0eactive_role_id\x18\v \x01(\tR\factiveRoleId\x12*\n" +
	"\x11is_platform_staff\x18\f \x01(\bR\x0fisPlatformStaff\x12C\n" +
	"\vmemberships\x18\r \x03(\v2!.gophercourier.auth.v1.MembershipR\vmemberships\x12>\n" +
	"\x1brequires_email_verification\x18\x0e \x01(\bR\x19requiresEmailVerification\"\x85\x03\n" +
	"\x0fRefreshResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12/\n" +
	"\x04user\x18\x03 \x01(\v2\x1b.gophercourier.auth.v1.UserR\x04user\x12\"\n" +
	"\ractive_org_id\x18\n" +
	" \x01(\tR\vactiveOrgId\x12$\n" +
	"\x0eactive_role_id\x18\v \x01(\tR\factiveRoleId\x12*\n" +
	"\x11is_platform_staff\x18\f \x01(\bR\x0fisPlatformStaff\x12C\n" +
	"\vmemberships\x18\r \x03(\v2!.gophercourier.auth.v1.MembershipR\vmemberships\x12>\n" +
	"\x1brequires_email_verification\x18\x0e \x01(\bR\x19requiresEmailVerification\"@\n" +
	"\rGetMeResponse\x12/\n" +
	"\x04user\x18\x01 \x01(\v2\x1b.gophercourier.auth.v1.UserR\x04user\"\xfb\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12%\n" +
	"\x0eemail_verified\x18\x05 \x01(\bR\remailVerified\x12*\n" +
	"\x11is_platform_staff\x18\x06 \x01(\bR\x0fisPlatformStaff\x12+\n" +
	"\x12last_active_org_id\x18\a \x01(\tR\x0flastActiveOrgId\"\xe9\x01\n" +
	"\n" +
	"Membership\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\borg_name\x18\x02 \x01(\tR\aorgName\x12\x19\n" +
	"\borg_slug\x18\x03 \x01(\tR\aorgSlug\x12\x1f\n" +
	"\vis_personal\x18\x04 \x01(\bR\n" +
	"isPersonal\x12\x17\n" +
	"\arole_id\x18\x05 \x01(\tR\x06roleId\x12\x1b\n" +
	"\trole_name\x18\x06 \x01(\tR\broleName\x127\n" +
	"\tjoined_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\")\n" +
	"\x10SwitchOrgRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"\xc7\x02\n" +
	"\x11SwitchOrgResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12/\n" +
	"\x04user\x18\x03 \x01(\v2\x1b.gophercourier.auth.v1.UserR\x04user\x12\"\n" +
	"\ractive_org_id\x18\n" +
	" \x01(\tR\vactiveOrgId\x12$\n" +
	"\x0eactive_role_id\x18\v \x01(\tR\factiveRoleId\x12*\n" +
	"\x11is_platform_staff\x18\f \x01(\bR\x0fisPlatformStaff\x12C\n" +
	"\vmemberships\x18\r \x03(\v2!.gophercourier.auth.v1.MembershipR\vmemberships\"\v\n" +
	"\tMeRequest\"\x83\x02\n" +
	"\n" +
	"MeResponse\x12/\n" +
	"\x04user\x18\x01 \x01(\v2\x1b.gophercourier.auth.v1.UserR\x04user\x12?\n" +
	"\n" +
	"active_org\x18\x02 \x01(\v2 .gophercourier.auth.v1.ActiveOrgR\tactiveOrg\x12C\n" +
	"\vmemberships\x18\x03 \x03(\v2!.gophercourier.auth.v1.MembershipR\vmemberships\x12>\n" +
	"\bsessions\x18\x04 \x03(\v2\".gophercourier.auth.v1.SessionViewR\bsessions\"\xaf\x01\n" +
	"\tActiveOrg\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\borg_name\x18\x02 \x01(\tR\aorgName\x12\x19\n" +
	"\borg_slug\x18\x03 \x01(\tR\aorgSlug\x12\x1f\n" +
	"\vis_personal\x18\x04 \x01(\bR\n" +
	"isPersonal\x12\x17\n" +
	"\arole_id\x18\x05 \x01(\tR\x06roleId\x12\x1b\n" +
	"\trole_name\x18\x06 \x01(\tR\broleName\"\xc6\x01\n" +
	"\vSessionView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12<\n" +
	"\flast_used_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x12\x1d\n" +
	"\n" +
	"is_current\x18\x06 \x01(\bR\tisCurrent\"\x0f\n" +
	"\rMyOrgsRequest\"U\n" +
	"\x0eMyOrgsResponse\x12C\n" +
	"\vmemberships\x18\x01 \x03(\v2!.gophercourier.auth.v1.MembershipR\vmemberships\"*\n" +
	"\x12VerifyEmailRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x15\n" +
	"\x13VerifyEmailResponse\"\x1b\n" +
	"\x19ResendVerificationRequest\"\x1c\n" +
	"\x1aResendVerificationResponse\"\x91\x01\n" +
	"\x15ChangePasswordRequest\x12!\n" +
	"\fold_password\x18\x01 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\x122\n" +
	"\x15revoke_other_sessions\x18\x03 \x01(\bR\x13revokeOtherSessions\"\x18\n" +
	"\x16ChangePasswordResponse\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse\"5\n" +
	"\x14RevokeSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x17\n" +
	"\x15RevokeSessionResponse\"\x12\n" +
	"\x10LogoutAllRequest\"8\n" +
	"\x11LogoutAllResponse\x12#\n" +
	"\rrevoked_count\x18\x01 \x01(\x05R\frevokedCount2\xe1\t\n" +
	"\vAuthService\x12[\n" +
	"\bRegister\x12&.gophercourier.auth.v1.RegisterRequest\x1a'.gophercourier.auth.v1.RegisterResponse\x12R\n" +
	"\x05Login\x12#.gophercourier.auth.v1.LoginRequest\x1a$.gophercourier.auth.v1.LoginResponse\x12X\n" +
	"\aRefresh\x12%.gophercourier.auth.v1.RefreshRequest\x1a&.gophercourier.auth.v1.RefreshResponse\x12R\n" +
	"\x05GetMe\x12#.gophercourier.auth.v1.GetMeRequest\x1a$.gophercourier.auth.v1.GetMeResponse\x12^\n" +
	"\tSwitchOrg\x12'.gophercourier.auth.v1.SwitchOrgRequest\x1a(.gophercourier.auth.v1.SwitchOrgResponse\x12I\n" +
	"\x02Me\x12 .gophercourier.auth.v1.MeRequest\x1a!.gophercourier.auth.v1.MeResponse\x12U\n" +
	"\x06MyOrgs\x12$.gophercourier.auth.v1.MyOrgsRequest\x1a%.gophercourier.auth.v1.MyOrgsResponse\x12d\n" +
	"\vVerifyEmail\x12).gophercourier.auth.v1.VerifyEmailRequest\x1a*.gophercourier.auth.v1.VerifyEmailResponse\x12y\n" +
	"\x12ResendVerification\x120.gophercourier.auth.v1.ResendVerificationRequest\x1a1.gophercourier.auth.v1.ResendVerificationResponse\x12m\n" +
	"\x0eChangePassword\x12,.gophercourier.auth.v1.ChangePasswordRequest\x1a-.gophercourier.auth.v1.ChangePasswordResponse\x12U\n" +
	"\x06Logout\x12$.gophercourier.auth.v1.LogoutRequest\x1a%.gophercourier.auth.v1.LogoutResponse\x12j\n" +
	"\rRevokeSession\x12+.gophercourier.auth.v1.RevokeSessionRequest\x1a,.gophercourier.auth.v1.RevokeSessionResponse\x12^\n" +
	"\tLogoutAll\x12'.gophercourier.auth.v1.LogoutAllRequest\x1a(.gophercourier.auth.v1.LogoutAllResponseB\xd9\x01\n" +
	"\x19com.gophercourier.auth.v1B\tAuthProtoP\x01Z;github.com/tetiva-app/proto/go/gophercourier/auth/v1;authv1\xa2\x02\x03GAX\xaa\x02\x15Gophercourier.Auth.V1\xca\x02\x15Gophercourier\\Auth\\V1\xe2\x02!Gophercourier\\Auth\\V1\\GPBMetadata\xea\x02\x17Gophercourier::Auth::V1b\x06proto3"

var file_gophercourier_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_gophercourier_auth_v1_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),            // 0: gophercourier.auth.v1.RegisterRequest
	(*LoginRequest)(nil),               // 1: gophercourier.auth.v1.LoginRequest
	(*RefreshRequest)(nil),             // 2: gophercourier.auth.v1.RefreshRequest
	(*GetMeRequest)(nil),               // 3: gophercourier.auth.v1.GetMeRequest
	(*RegisterResponse)(nil),           // 4: gophercourier.auth.v1.RegisterResponse
	(*LoginResponse)(nil),              // 5: gophercourier.auth.v1.LoginResponse
	(*RefreshResponse)(nil),            // 6: gophercourier.auth.v1.RefreshResponse
	(*GetMeResponse)(nil),              // 7: gophercourier.auth.v1.GetMeResponse
	(*User)(nil),                       // 8: gophercourier.auth.v1.User
	(*Membership)(nil),                 // 9: gophercourier.auth.v1.Membership
	(*SwitchOrgRequest)(nil),           // 10: gophercourier.auth.v1.SwitchOrgRequest
	(*SwitchOrgResponse)(nil),          // 11: gophercourier.auth.v1.SwitchOrgResponse
	(*MeRequest)(nil),                  // 12: gophercourier.auth.v1.MeRequest
	(*MeResponse)(nil),                 // 13: gophercourier.auth.v1.MeResponse
	(*ActiveOrg)(nil),                  // 14: gophercourier.auth.v1.ActiveOrg
	(*SessionView)(nil),                // 15: gophercourier.auth.v1.SessionView
	(*MyOrgsRequest)(nil),              // 16: gophercourier.auth.v1.MyOrgsRequest
	(*MyOrgsResponse)(nil),             // 17: gophercourier.auth.v1.MyOrgsResponse
	(*VerifyEmailRequest)(nil),         // 18: gophercourier.auth.v1.VerifyEmailRequest
	(*VerifyEmailResponse)(nil),        // 19: gophercourier.auth.v1.VerifyEmailResponse
	(*ResendVerificationRequest)(nil),  // 20: gophercourier.auth.v1.ResendVerificationRequest
	(*ResendVerificationResponse)(nil), // 21: gophercourier.auth.v1.ResendVerificationResponse
	(*ChangePasswordRequest)(nil),      // 22: gophercourier.auth.v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),     // 23: gophercourier.auth.v1.ChangePasswordResponse
	(*LogoutRequest)(nil),              // 24: gophercourier.auth.v1.LogoutRequest
	(*LogoutResponse)(nil),             // 25: gophercourier.auth.v1.LogoutResponse
	(*RevokeSessionRequest)(nil),       // 26: gophercourier.auth.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),      // 27: gophercourier.auth.v1.RevokeSessionResponse
	(*LogoutAllRequest)(nil),           // 28: gophercourier.auth.v1.LogoutAllRequest
	(*LogoutAllResponse)(nil),          // 29: gophercourier.auth.v1.LogoutAllResponse
	(*timestamppb.Timestamp)(nil),      // 30: google.protobuf.Timestamp
}
var file_gophercourier_auth_v1_auth_proto_depIdxs = []int32{
	8,  // 0: gophercourier.auth.v1.RegisterResponse.user:type_name -> gophercourier.auth.v1.User
	9,  // 1: gophercourier.auth.v1.RegisterResponse.memberships:type_name -> gophercourier.auth.v1.Membership
	8,  // 2: gophercourier.auth.v1.LoginResponse.user:type_name -> gophercourier.auth.v1.User
	9,  // 3: gophercourier.auth.v1.LoginResponse.memberships:type_name -> gophercourier.auth.v1.Membership
	8,  // 4: gophercourier.auth.v1.RefreshResponse.user:type_name -> gophercourier.auth.v1.User
	9,  // 5: gophercourier.auth.v1.RefreshResponse.memberships:type_name -> gophercourier.auth.v1.Membership
	8,  // 6: gophercourier.auth.v1.GetMeResponse.user:type_name -> gophercourier.auth.v1.User
	30, // 7: gophercourier.auth.v1.User.created_at:type_name -> google.protobuf.Timestamp
	30, // 8: gophercourier.auth.v1.Membership.joined_at:type_name -> google.protobuf.Timestamp
	8,  // 9: gophercourier.auth.v1.SwitchOrgResponse.user:type_name -> gophercourier.auth.v1.User
	9,  // 10: gophercourier.auth.v1.SwitchOrgResponse.memberships:type_name -> gophercourier.auth.v1.Membership
	8,  // 11: gophercourier.auth.v1.MeResponse.user:type_name -> gophercourier.auth.v1.User
	14, // 12: gophercourier.auth.v1.MeResponse.active_org:type_name -> gophercourier.auth.v1.ActiveOrg
	9,  // 13: gophercourier.auth.v1.MeResponse.memberships:type_name -> gophercourier.auth.v1.Membership
	15, // 14: gophercourier.auth.v1.MeResponse.sessions:type_name -> gophercourier.auth.v1.SessionView
	30, // 15: gophercourier.auth.v1.SessionView.last_used_at:type_name -> google.protobuf.Timestamp
	9,  // 16: gophercourier.auth.v1.MyOrgsResponse.memberships:type_name -> gophercourier.auth.v1.Membership
	0,  // 17: gophercourier.auth.v1.AuthService.Register:input_type -> gophercourier.auth.v1.RegisterRequest
	1,  // 18: gophercourier.auth.v1.AuthService.Login:input_type -> gophercourier.auth.v1.LoginRequest
	2,  // 19: gophercourier.auth.v1.AuthService.Refresh:input_type -> gophercourier.auth.v1.RefreshRequest
	3,  // 20: gophercourier.auth.v1.AuthService.GetMe:input_type -> gophercourier.auth.v1.GetMeRequest
	10, // 21: gophercourier.auth.v1.AuthService.SwitchOrg:input_type -> gophercourier.auth.v1.SwitchOrgRequest
	12, // 22: gophercourier.auth.v1.AuthService.Me:input_type -> gophercourier.auth.v1.MeRequest
	16, // 23: gophercourier.auth.v1.AuthService.MyOrgs:input_type -> gophercourier.auth.v1.MyOrgsRequest
	18, // 24: gophercourier.auth.v1.AuthService.VerifyEmail:input_type -> gophercourier.auth.v1.VerifyEmailRequest
	20, // 25: gophercourier.auth.v1.AuthService.ResendVerification:input_type -> gophercourier.auth.v1.ResendVerificationRequest
	22, // 26: gophercourier.auth.v1.AuthService.ChangePassword:input_type -> gophercourier.auth.v1.ChangePasswordRequest
	24, // 27: gophercourier.auth.v1.AuthService.Logout:input_type -> gophercourier.auth.v1.LogoutRequest
	26, // 28: gophercourier.auth.v1.AuthService.RevokeSession:input_type -> gophercourier.auth.v1.RevokeSessionRequest
	28, // 29: gophercourier.auth.v1.AuthService.LogoutAll:input_type -> gophercourier.auth.v1.LogoutAllRequest
	4,  // 30: gophercourier.auth.v1.AuthService.Register:output_type -> gophercourier.auth.v1.RegisterResponse
	5,  // 31: gophercourier.auth.v1.AuthService.Login:output_type -> gophercourier.auth.v1.LoginResponse
	6,  // 32: gophercourier.auth.v1.AuthService.Refresh:output_type -> gophercourier.auth.v1.RefreshResponse
	7,  // 33: gophercourier.auth.v1.AuthService.GetMe:output_type -> gophercourier.auth.v1.GetMeResponse
	11, // 34: gophercourier.auth.v1.AuthService.SwitchOrg:output_type -> gophercourier.auth.v1.SwitchOrgResponse
	13, // 35: gophercourier.auth.v1.AuthService.Me:output_type -> gophercourier.auth.v1.MeResponse
	17, // 36: gophercourier.auth.v1.AuthService.MyOrgs:output_type -> gophercourier.auth.v1.MyOrgsResponse
	19, // 37: gophercourier.auth.v1.AuthService.VerifyEmail:output_type -> gophercourier.auth.v1.VerifyEmailResponse
	21, // 38: gophercourier.auth.v1.AuthService.ResendVerification:output_type -> gophercourier.auth.v1.ResendVerificationResponse
	23, // 39: gophercourier.auth.v1.AuthService.ChangePassword:output_type -> gophercourier.auth.v1.ChangePasswordResponse
	25, // 40: gophercourier.auth.v1.AuthService.Logout:output_type -> gophercourier.auth.v1.LogoutResponse
	27, // 41: gophercourier.auth.v1.AuthService.RevokeSession:output_type -> gophercourier.auth.v1.RevokeSessionResponse
	29, // 42: gophercourier.auth.v1.AuthService.LogoutAll:output_type -> gophercourier.auth.v1.LogoutAllResponse
	30, // [30:43] is the sub-list for method output_type
	17, // [17:30] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_gophercourier_auth_v1_auth_proto_init() }
func file_gophercourier_auth_v1_auth_proto_init() {
	if File_gophercourier_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophercourier_auth_v1_auth_proto_rawDesc), len(file_gophercourier_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophercourier_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_gophercourier_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_gophercourier_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_gophercourier_auth_v1_auth_proto = out.File
	file_gophercourier_auth_v1_auth_proto_goTypes = nil
	file_gophercourier_auth_v1_auth_proto_depIdxs = nil
}
