// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gophercourier/org/v1/org.proto

package orgv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Org struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Name        string                 `protobuf:"bytes,2,opt,name=name,proto3"`
	xxx_hidden_Slug        string                 `protobuf:"bytes,3,opt,name=slug,proto3"`
	xxx_hidden_OwnerUserId string                 `protobuf:"bytes,4,opt,name=owner_user_id,json=ownerUserId,proto3"`
	xxx_hidden_IsPersonal  bool                   `protobuf:"varint,5,opt,name=is_personal,json=isPersonal,proto3"`
	xxx_hidden_Settings    *OrgSettings           `protobuf:"bytes,6,opt,name=settings,proto3"`
	xxx_hidden_Description string                 `protobuf:"bytes,7,opt,name=description,proto3"`
	xxx_hidden_IconUrl     string                 `protobuf:"bytes,8,opt,name=icon_url,json=iconUrl,proto3"`
	xxx_hidden_Version     int32                  `protobuf:"varint,9,opt,name=version,proto3"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Org) Reset() {
	*x = Org{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Org) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Org) ProtoMessage() {}

func (x *Org) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Org) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Org) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Org) GetSlug() string {
	if x != nil {
		return x.xxx_hidden_Slug
	}
	return ""
}

func (x *Org) GetOwnerUserId() string {
	if x != nil {
		return x.xxx_hidden_OwnerUserId
	}
	return ""
}

func (x *Org) GetIsPersonal() bool {
	if x != nil {
		return x.xxx_hidden_IsPersonal
	}
	return false
}

func (x *Org) GetSettings() *OrgSettings {
	if x != nil {
		return x.xxx_hidden_Settings
	}
	return nil
}

func (x *Org) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *Org) GetIconUrl() string {
	if x != nil {
		return x.xxx_hidden_IconUrl
	}
	return ""
}

func (x *Org) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Org) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Org) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Org) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Org) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Org) SetSlug(v string) {
	x.xxx_hidden_Slug = v
}

func (x *Org) SetOwnerUserId(v string) {
	x.xxx_hidden_OwnerUserId = v
}

func (x *Org) SetIsPersonal(v bool) {
	x.xxx_hidden_IsPersonal = v
}

func (x *Org) SetSettings(v *OrgSettings) {
	x.xxx_hidden_Settings = v
}

func (x *Org) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *Org) SetIconUrl(v string) {
	x.xxx_hidden_IconUrl = v
}

func (x *Org) SetVersion(v int32) {
	x.xxx_hidden_Version = v
}

func (x *Org) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Org) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Org) HasSettings() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Settings != nil
}

func (x *Org) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Org) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Org) ClearSettings() {
	x.xxx_hidden_Settings = nil
}

func (x *Org) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Org) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type Org_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          string
	Name        string
	Slug        string
	OwnerUserId string
	IsPersonal  bool
	Settings    *OrgSettings
	Description string
	IconUrl     string
	Version     int32
	CreatedAt   *timestamppb.Timestamp
	UpdatedAt   *timestamppb.Timestamp
}

func (b0 Org_builder) Build() *Org {
	m0 := &Org{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Slug = b.Slug
	x.xxx_hidden_OwnerUserId = b.OwnerUserId
	x.xxx_hidden_IsPersonal = b.IsPersonal
	x.xxx_hidden_Settings = b.Settings
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_IconUrl = b.IconUrl
	x.xxx_hidden_Version = b.Version
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

type OrgSettings struct {
	state                                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AllowMembersCreateWorkspaces bool                   `protobuf:"varint,1,opt,name=allow_members_create_workspaces,json=allowMembersCreateWorkspaces,proto3"`
	xxx_hidden_RegistrationInviteOnly       bool                   `protobuf:"varint,2,opt,name=registration_invite_only,json=registrationInviteOnly,proto3"`
	xxx_hidden_DefaultMemberRoleId          string                 `protobuf:"bytes,3,opt,name=default_member_role_id,json=defaultMemberRoleId,proto3"`
	xxx_hidden_DefaultWorkspaceRoleId       string                 `protobuf:"bytes,4,opt,name=default_workspace_role_id,json=defaultWorkspaceRoleId,proto3"`
	unknownFields                           protoimpl.UnknownFields
	sizeCache                               protoimpl.SizeCache
}

func (x *OrgSettings) Reset() {
	*x = OrgSettings{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgSettings) ProtoMessage() {}

func (x *OrgSettings) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OrgSettings) GetAllowMembersCreateWorkspaces() bool {
	if x != nil {
		return x.xxx_hidden_AllowMembersCreateWorkspaces
	}
	return false
}

func (x *OrgSettings) GetRegistrationInviteOnly() bool {
	if x != nil {
		return x.xxx_hidden_RegistrationInviteOnly
	}
	return false
}

func (x *OrgSettings) GetDefaultMemberRoleId() string {
	if x != nil {
		return x.xxx_hidden_DefaultMemberRoleId
	}
	return ""
}

func (x *OrgSettings) GetDefaultWorkspaceRoleId() string {
	if x != nil {
		return x.xxx_hidden_DefaultWorkspaceRoleId
	}
	return ""
}

func (x *OrgSettings) SetAllowMembersCreateWorkspaces(v bool) {
	x.xxx_hidden_AllowMembersCreateWorkspaces = v
}

func (x *OrgSettings) SetRegistrationInviteOnly(v bool) {
	x.xxx_hidden_RegistrationInviteOnly = v
}

func (x *OrgSettings) SetDefaultMemberRoleId(v string) {
	x.xxx_hidden_DefaultMemberRoleId = v
}

func (x *OrgSettings) SetDefaultWorkspaceRoleId(v string) {
	x.xxx_hidden_DefaultWorkspaceRoleId = v
}

type OrgSettings_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AllowMembersCreateWorkspaces bool
	RegistrationInviteOnly       bool
	DefaultMemberRoleId          string
	DefaultWorkspaceRoleId       string
}

func (b0 OrgSettings_builder) Build() *OrgSettings {
	m0 := &OrgSettings{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AllowMembersCreateWorkspaces = b.AllowMembersCreateWorkspaces
	x.xxx_hidden_RegistrationInviteOnly = b.RegistrationInviteOnly
	x.xxx_hidden_DefaultMemberRoleId = b.DefaultMemberRoleId
	x.xxx_hidden_DefaultWorkspaceRoleId = b.DefaultWorkspaceRoleId
	return m0
}

type CreateRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Slug        string                 `protobuf:"bytes,2,opt,name=slug,proto3"`
	xxx_hidden_Description string                 `protobuf:"bytes,3,opt,name=description,proto3"`
	xxx_hidden_IconUrl     string                 `protobuf:"bytes,4,opt,name=icon_url,json=iconUrl,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *CreateRequest) GetSlug() string {
	if x != nil {
		return x.xxx_hidden_Slug
	}
	return ""
}

func (x *CreateRequest) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *CreateRequest) GetIconUrl() string {
	if x != nil {
		return x.xxx_hidden_IconUrl
	}
	return ""
}

func (x *CreateRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *CreateRequest) SetSlug(v string) {
	x.xxx_hidden_Slug = v
}

func (x *CreateRequest) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *CreateRequest) SetIconUrl(v string) {
	x.xxx_hidden_IconUrl = v
}

type CreateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name        string
	Slug        string
	Description string
	IconUrl     string
}

func (b0 CreateRequest_builder) Build() *CreateRequest {
	m0 := &CreateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Slug = b.Slug
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_IconUrl = b.IconUrl
	return m0
}

type CreateResponse struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Org *Org                   `protobuf:"bytes,1,opt,name=org,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateResponse) GetOrg() *Org {
	if x != nil {
		return x.xxx_hidden_Org
	}
	return nil
}

func (x *CreateResponse) SetOrg(v *Org) {
	x.xxx_hidden_Org = v
}

func (x *CreateResponse) HasOrg() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Org != nil
}

func (x *CreateResponse) ClearOrg() {
	x.xxx_hidden_Org = nil
}

type CreateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Org *Org
}

func (b0 CreateResponse_builder) Build() *CreateResponse {
	m0 := &CreateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Org = b.Org
	return m0
}

type UpdateRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId       string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
	xxx_hidden_Slug        *string                `protobuf:"bytes,3,opt,name=slug,proto3,oneof"`
	xxx_hidden_Description *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof"`
	xxx_hidden_IconUrl     *string                `protobuf:"bytes,5,opt,name=icon_url,json=iconUrl,proto3,oneof"`
	xxx_hidden_Settings    *OrgSettings           `protobuf:"bytes,6,opt,name=settings,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateRequest) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *UpdateRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *UpdateRequest) GetSlug() string {
	if x != nil {
		if x.xxx_hidden_Slug != nil {
			return *x.xxx_hidden_Slug
		}
		return ""
	}
	return ""
}

func (x *UpdateRequest) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *UpdateRequest) GetIconUrl() string {
	if x != nil {
		if x.xxx_hidden_IconUrl != nil {
			return *x.xxx_hidden_IconUrl
		}
		return ""
	}
	return ""
}

func (x *UpdateRequest) GetSettings() *OrgSettings {
	if x != nil {
		return x.xxx_hidden_Settings
	}
	return nil
}

func (x *UpdateRequest) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

func (x *UpdateRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *UpdateRequest) SetSlug(v string) {
	x.xxx_hidden_Slug = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *UpdateRequest) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *UpdateRequest) SetIconUrl(v string) {
	x.xxx_hidden_IconUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *UpdateRequest) SetSettings(v *OrgSettings) {
	x.xxx_hidden_Settings = v
}

func (x *UpdateRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateRequest) HasSlug() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UpdateRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UpdateRequest) HasIconUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *UpdateRequest) HasSettings() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Settings != nil
}

func (x *UpdateRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *UpdateRequest) ClearSlug() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Slug = nil
}

func (x *UpdateRequest) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Description = nil
}

func (x *UpdateRequest) ClearIconUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_IconUrl = nil
}

func (x *UpdateRequest) ClearSettings() {
	x.xxx_hidden_Settings = nil
}

type UpdateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OrgId       string
	Name        *string
	Slug        *string
	Description *string
	IconUrl     *string
	Settings    *OrgSettings
}

func (b0 UpdateRequest_builder) Build() *UpdateRequest {
	m0 := &UpdateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Name = b.Name
	}
	if b.Slug != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Slug = b.Slug
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Description = b.Description
	}
	if b.IconUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_IconUrl = b.IconUrl
	}
	x.xxx_hidden_Settings = b.Settings
	return m0
}

type UpdateResponse struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Org *Org                   `protobuf:"bytes,1,opt,name=org,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateResponse) GetOrg() *Org {
	if x != nil {
		return x.xxx_hidden_Org
	}
	return nil
}

func (x *UpdateResponse) SetOrg(v *Org) {
	x.xxx_hidden_Org = v
}

func (x *UpdateResponse) HasOrg() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Org != nil
}

func (x *UpdateResponse) ClearOrg() {
	x.xxx_hidden_Org = nil
}

type UpdateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Org *Org
}

func (b0 UpdateResponse_builder) Build() *UpdateResponse {
	m0 := &UpdateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Org = b.Org
	return m0
}

type DeleteRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteRequest) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *DeleteRequest) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

type DeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OrgId string
}

func (b0 DeleteRequest_builder) Build() *DeleteRequest {
	m0 := &DeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	return m0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteResponse_builder) Build() *DeleteResponse {
	m0 := &DeleteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRequest) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *GetRequest) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

type GetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OrgId string
}

func (b0 GetRequest_builder) Build() *GetRequest {
	m0 := &GetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	return m0
}

type GetResponse struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Org *Org                   `protobuf:"bytes,1,opt,name=org,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetResponse) GetOrg() *Org {
	if x != nil {
		return x.xxx_hidden_Org
	}
	return nil
}

func (x *GetResponse) SetOrg(v *Org) {
	x.xxx_hidden_Org = v
}

func (x *GetResponse) HasOrg() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Org != nil
}

func (x *GetResponse) ClearOrg() {
	x.xxx_hidden_Org = nil
}

type GetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Org *Org
}

func (b0 GetResponse_builder) Build() *GetResponse {
	m0 := &GetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Org = b.Org
	return m0
}

type ListMineRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMineRequest) Reset() {
	*x = ListMineRequest{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMineRequest) ProtoMessage() {}

func (x *ListMineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListMineRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListMineRequest_builder) Build() *ListMineRequest {
	m0 := &ListMineRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListMineResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Orgs *[]*OrgWithRole        `protobuf:"bytes,1,rep,name=orgs,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListMineResponse) Reset() {
	*x = ListMineResponse{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMineResponse) ProtoMessage() {}

func (x *ListMineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListMineResponse) GetOrgs() []*OrgWithRole {
	if x != nil {
		if x.xxx_hidden_Orgs != nil {
			return *x.xxx_hidden_Orgs
		}
	}
	return nil
}

func (x *ListMineResponse) SetOrgs(v []*OrgWithRole) {
	x.xxx_hidden_Orgs = &v
}

type ListMineResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Orgs []*OrgWithRole
}

func (b0 ListMineResponse_builder) Build() *ListMineResponse {
	m0 := &ListMineResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Orgs = &b.Orgs
	return m0
}

type OrgWithRole struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Org      *Org                   `protobuf:"bytes,1,opt,name=org,proto3"`
	xxx_hidden_RoleId   string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3"`
	xxx_hidden_IsActive bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OrgWithRole) Reset() {
	*x = OrgWithRole{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgWithRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgWithRole) ProtoMessage() {}

func (x *OrgWithRole) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OrgWithRole) GetOrg() *Org {
	if x != nil {
		return x.xxx_hidden_Org
	}
	return nil
}

func (x *OrgWithRole) GetRoleId() string {
	if x != nil {
		return x.xxx_hidden_RoleId
	}
	return ""
}

func (x *OrgWithRole) GetIsActive() bool {
	if x != nil {
		return x.xxx_hidden_IsActive
	}
	return false
}

func (x *OrgWithRole) SetOrg(v *Org) {
	x.xxx_hidden_Org = v
}

func (x *OrgWithRole) SetRoleId(v string) {
	x.xxx_hidden_RoleId = v
}

func (x *OrgWithRole) SetIsActive(v bool) {
	x.xxx_hidden_IsActive = v
}

func (x *OrgWithRole) HasOrg() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Org != nil
}

func (x *OrgWithRole) ClearOrg() {
	x.xxx_hidden_Org = nil
}

type OrgWithRole_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Org      *Org
	RoleId   string
	IsActive bool
}

func (b0 OrgWithRole_builder) Build() *OrgWithRole {
	m0 := &OrgWithRole{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Org = b.Org
	x.xxx_hidden_RoleId = b.RoleId
	x.xxx_hidden_IsActive = b.IsActive
	return m0
}

type ListMembersRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId  string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	xxx_hidden_Cursor string                 `protobuf:"bytes,2,opt,name=cursor,proto3"`
	xxx_hidden_Limit  int32                  `protobuf:"varint,3,opt,name=limit,proto3"`
	xxx_hidden_RoleId string                 `protobuf:"bytes,4,opt,name=role_id,json=roleId,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListMembersRequest) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *ListMembersRequest) GetCursor() string {
	if x != nil {
		return x.xxx_hidden_Cursor
	}
	return ""
}

func (x *ListMembersRequest) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListMembersRequest) GetRoleId() string {
	if x != nil {
		return x.xxx_hidden_RoleId
	}
	return ""
}

func (x *ListMembersRequest) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

func (x *ListMembersRequest) SetCursor(v string) {
	x.xxx_hidden_Cursor = v
}

func (x *ListMembersRequest) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
}

func (x *ListMembersRequest) SetRoleId(v string) {
	x.xxx_hidden_RoleId = v
}

type ListMembersRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OrgId  string
	Cursor string
	Limit  int32
	RoleId string
}

func (b0 ListMembersRequest_builder) Build() *ListMembersRequest {
	m0 := &ListMembersRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	x.xxx_hidden_Cursor = b.Cursor
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_RoleId = b.RoleId
	return m0
}

type OrgMember struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId      string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3"`
	xxx_hidden_Email       string                 `protobuf:"bytes,2,opt,name=email,proto3"`
	xxx_hidden_Name        string                 `protobuf:"bytes,3,opt,name=name,proto3"`
	xxx_hidden_RoleId      string                 `protobuf:"bytes,4,opt,name=role_id,json=roleId,proto3"`
	xxx_hidden_RoleName    string                 `protobuf:"bytes,5,opt,name=role_name,json=roleName,proto3"`
	xxx_hidden_JoinedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=joined_at,json=joinedAt,proto3"`
	xxx_hidden_UserDeleted bool                   `protobuf:"varint,7,opt,name=user_deleted,json=userDeleted,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OrgMember) Reset() {
	*x = OrgMember{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgMember) ProtoMessage() {}

func (x *OrgMember) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OrgMember) GetUserId() string {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return ""
}

func (x *OrgMember) GetEmail() string {
	if x != nil {
		return x.xxx_hidden_Email
	}
	return ""
}

func (x *OrgMember) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *OrgMember) GetRoleId() string {
	if x != nil {
		return x.xxx_hidden_RoleId
	}
	return ""
}

func (x *OrgMember) GetRoleName() string {
	if x != nil {
		return x.xxx_hidden_RoleName
	}
	return ""
}

func (x *OrgMember) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_JoinedAt
	}
	return nil
}

func (x *OrgMember) GetUserDeleted() bool {
	if x != nil {
		return x.xxx_hidden_UserDeleted
	}
	return false
}

func (x *OrgMember) SetUserId(v string) {
	x.xxx_hidden_UserId = v
}

func (x *OrgMember) SetEmail(v string) {
	x.xxx_hidden_Email = v
}

func (x *OrgMember) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *OrgMember) SetRoleId(v string) {
	x.xxx_hidden_RoleId = v
}

func (x *OrgMember) SetRoleName(v string) {
	x.xxx_hidden_RoleName = v
}

func (x *OrgMember) SetJoinedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_JoinedAt = v
}

func (x *OrgMember) SetUserDeleted(v bool) {
	x.xxx_hidden_UserDeleted = v
}

func (x *OrgMember) HasJoinedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_JoinedAt != nil
}

func (x *OrgMember) ClearJoinedAt() {
	x.xxx_hidden_JoinedAt = nil
}

type OrgMember_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId   string
	Email    string
	Name     string
	RoleId   string
	RoleName string
	JoinedAt *timestamppb.Timestamp
	// user_deleted=true means the underlying User row is missing or soft-deleted.
	// In that case email/name will be empty — frontend should render as
	// "(deleted user)" or similar disambiguated state.
	UserDeleted bool
}

func (b0 OrgMember_builder) Build() *OrgMember {
	m0 := &OrgMember{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_Email = b.Email
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_RoleId = b.RoleId
	x.xxx_hidden_RoleName = b.RoleName
	x.xxx_hidden_JoinedAt = b.JoinedAt
	x.xxx_hidden_UserDeleted = b.UserDeleted
	return m0
}

type ListMembersResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Members    *[]*OrgMember          `protobuf:"bytes,1,rep,name=members,proto3"`
	xxx_hidden_NextCursor string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListMembersResponse) GetMembers() []*OrgMember {
	if x != nil {
		if x.xxx_hidden_Members != nil {
			return *x.xxx_hidden_Members
		}
	}
	return nil
}

func (x *ListMembersResponse) GetNextCursor() string {
	if x != nil {
		return x.xxx_hidden_NextCursor
	}
	return ""
}

func (x *ListMembersResponse) SetMembers(v []*OrgMember) {
	x.xxx_hidden_Members = &v
}

func (x *ListMembersResponse) SetNextCursor(v string) {
	x.xxx_hidden_NextCursor = v
}

type ListMembersResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Members    []*OrgMember
	NextCursor string
}

func (b0 ListMembersResponse_builder) Build() *ListMembersResponse {
	m0 := &ListMembersResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Members = &b.Members
	x.xxx_hidden_NextCursor = b.NextCursor
	return m0
}

type ListUsersByIDsRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId   string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	xxx_hidden_UserIds []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListUsersByIDsRequest) Reset() {
	*x = ListUsersByIDsRequest{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersByIDsRequest) ProtoMessage() {}

func (x *ListUsersByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListUsersByIDsRequest) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *ListUsersByIDsRequest) GetUserIds() []string {
	if x != nil {
		return x.xxx_hidden_UserIds
	}
	return nil
}

func (x *ListUsersByIDsRequest) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

func (x *ListUsersByIDsRequest) SetUserIds(v []string) {
	x.xxx_hidden_UserIds = v
}

type ListUsersByIDsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Org the caller is acting within. Required.
	OrgId string
	// Up to 100 user IDs to look up. Server clamps to 100; empty returns empty.
	UserIds []string
}

func (b0 ListUsersByIDsRequest_builder) Build() *ListUsersByIDsRequest {
	m0 := &ListUsersByIDsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	x.xxx_hidden_UserIds = b.UserIds
	return m0
}

type ListUsersByIDsResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Users *[]*OrgUser            `protobuf:"bytes,1,rep,name=users,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListUsersByIDsResponse) Reset() {
	*x = ListUsersByIDsResponse{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersByIDsResponse) ProtoMessage() {}

func (x *ListUsersByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListUsersByIDsResponse) GetUsers() []*OrgUser {
	if x != nil {
		if x.xxx_hidden_Users != nil {
			return *x.xxx_hidden_Users
		}
	}
	return nil
}

func (x *ListUsersByIDsResponse) SetUsers(v []*OrgUser) {
	x.xxx_hidden_Users = &v
}

type ListUsersByIDsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// One entry per requested ID that exists AND is a member of org_id.
	// Missing IDs (hard-deleted users, or users not in org) are simply absent.
	// Soft-deleted users ARE returned with is_deleted=true and empty email/name
	// (mirrors OrgMember.user_deleted semantics) — frontend uses this for
	// orphan-tolerant rendering (avatar "——", last-6 of user_id).
	Users []*OrgUser
}

func (b0 ListUsersByIDsResponse_builder) Build() *ListUsersByIDsResponse {
	m0 := &ListUsersByIDsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Users = &b.Users
	return m0
}

type OrgUser struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId    string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3"`
	xxx_hidden_Email     string                 `protobuf:"bytes,2,opt,name=email,proto3"`
	xxx_hidden_Name      string                 `protobuf:"bytes,3,opt,name=name,proto3"`
	xxx_hidden_IsDeleted bool                   `protobuf:"varint,4,opt,name=is_deleted,json=isDeleted,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OrgUser) Reset() {
	*x = OrgUser{}
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgUser) ProtoMessage() {}

func (x *OrgUser) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_org_v1_org_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OrgUser) GetUserId() string {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return ""
}

func (x *OrgUser) GetEmail() string {
	if x != nil {
		return x.xxx_hidden_Email
	}
	return ""
}

func (x *OrgUser) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *OrgUser) GetIsDeleted() bool {
	if x != nil {
		return x.xxx_hidden_IsDeleted
	}
	return false
}

func (x *OrgUser) SetUserId(v string) {
	x.xxx_hidden_UserId = v
}

func (x *OrgUser) SetEmail(v string) {
	x.xxx_hidden_Email = v
}

func (x *OrgUser) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *OrgUser) SetIsDeleted(v bool) {
	x.xxx_hidden_IsDeleted = v
}

type OrgUser_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId    string
	Email     string
	Name      string
	IsDeleted bool
}

func (b0 OrgUser_builder) Build() *OrgUser {
	m0 := &OrgUser{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_Email = b.Email
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_IsDeleted = b.IsDeleted
	return m0
}

var File_gophercourier_org_v1_org_proto protoreflect.FileDescriptor

const file_gophercourier_org_v1_org_proto_rawDesc = "" +
	"\n" +
	"\x1egophercourier/org/v1/org.proto\x12\x14gophercourier.org.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x03\n" +
	"\x03Org\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\"\n" +
	"\rowner_user_id\x18\x04 \x01(\tR\vownerUserId\x12\x1f\n" +
	"\vis_personal\x18\x05 \x01(\bR\n" +
	"isPersonal\x12=\n" +
	"\bsettings\x18\x06 \x01(\v2!.gophercourier.org.v1.OrgSettingsR\bsettings\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x19\n" +
	"\bicon_url\x18\b \x01(\tR\aiconUrl\x12\x18\n" +
	"\aversion\x18\t \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfe\x01\n" +
	"\vOrgSettings\x12E\n" +
	"\x1fallow_members_create_workspaces\x18\x01 \x01(\bR\x1callowMembersCreateWorkspaces\x128\n" +
	"\x18registration_invite_only\x18\x02 \x01(\bR\x16registrationInviteOnly\x123\n" +
	"\x16default_member_role_id\x18\x03 \x01(\tR\x13defaultMemberRoleId\x129\n" +
	"\x19default_workspace_role_id\x18\x04 \x01(\tR\x16defaultWorkspaceRoleId\"t\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bicon_url\x18\x04 \x01(\tR\aiconUrl\"=\n" +
	"\x0eCreateResponse\x12+\n" +
	"\x03org\x18\x01 \x01(\v2\x19.gophercourier.org.v1.OrgR\x03org\"\x9f\x02\n" +
	"\rUpdateRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04slug\x18\x03 \x01(\tH\x01R\x04slug\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x02R\vdescription\x88\x01\x01\x12\x1e\n" +
	"\bicon_url\x18\x05 \x01(\tH\x03R\aiconUrl\x88\x01\x01\x12B\n" +
	"\bsettings\x18\x06 \x01(\v2!.gophercourier.org.v1.OrgSettingsH\x04R\bsettings\x88\x01\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_slugB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_icon_urlB\v\n" +
	"\t_settings\"=\n" +
	"\x0eUpdateResponse\x12+\n" +
	"\x03org\x18\x01 \x01(\v2\x19.gophercourier.org.v1.OrgR\x03org\"&\n" +
	"\rDeleteRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"\x10\n" +
	"\x0eDeleteResponse\"#\n" +
	"\n" +
	"GetRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\":\n" +
	"\vGetResponse\x12+\n" +
	"\x03org\x18\x01 \x01(\v2\x19.gophercourier.org.v1.OrgR\x03org\"\x11\n" +
	"\x0fListMineRequest\"I\n" +
	"\x10ListMineResponse\x125\n" +
	"\x04orgs\x18\x01 \x03(\v2!.gophercourier.org.v1.OrgWithRoleR\x04orgs\"p\n" +
	"\vOrgWithRole\x12+\n" +
	"\x03org\x18\x01 \x01(\v2\x19.gophercourier.org.v1.OrgR\x03org\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\"\x89\x01\n" +
	"\x12ListMembersRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x17\n" +
	"\arole_id\x18\x04 \x01(\tR\x06roleIdJ\x04\b\x05\x10\x06R\x0femail_substring\"\xe0\x01\n" +
	"\tOrgMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\arole_id\x18\x04 \x01(\tR\x06roleId\x12\x1b\n" +
	"\trole_name\x18\x05 \x01(\tR\broleName\x127\n" +
	"\tjoined_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x12!\n" +
	"\fuser_deleted\x18\a \x01(\bR\vuserDeleted\"q\n" +
	"\x13ListMembersResponse\x129\n" +
	"\amembers\x18\x01 \x03(\v2\x1f.gophercourier.org.v1.OrgMemberR\amembers\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"I\n" +
	"\x15ListUsersByIDsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\"M\n" +
	"\x16ListUsersByIDsResponse\x123\n" +
	"\x05users\x18\x01 \x03(\v2\x1d.gophercourier.org.v1.OrgUserR\x05users\"k\n" +
	"\aOrgUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x04 \x01(\bR\tisDeleted2\x83\x05\n" +
	"\n" +
	"OrgService\x12S\n" +
	"\x06Create\x12#.gophercourier.org.v1.CreateRequest\x1a$.gophercourier.org.v1.CreateResponse\x12S\n" +
	"\x06Update\x12#.gophercourier.org.v1.UpdateRequest\x1a$.gophercourier.org.v1.UpdateResponse\x12S\n" +
	"\x06Delete\x12#.gophercourier.org.v1.DeleteRequest\x1a$.gophercourier.org.v1.DeleteResponse\x12J\n" +
	"\x03Get\x12 .gophercourier.org.v1.GetRequest\x1a!.gophercourier.org.v1.GetResponse\x12Y\n" +
	"\bListMine\x12%.gophercourier.org.v1.ListMineRequest\x1a&.gophercourier.org.v1.ListMineResponse\x12b\n" +
	"\vListMembers\x12(.gophercourier.org.v1.ListMembersRequest\x1a).gophercourier.org.v1.ListMembersResponse\x12k\n" +
	"\x0eListUsersByIDs\x12+.gophercourier.org.v1.ListUsersByIDsRequest\x1a,.gophercourier.org.v1.ListUsersByIDsResponseB\xd1\x01\n" +
	"\x18com.gophercourier.org.v1B\bOrgProtoP\x01Z9github.com/tetiva-app/proto/go/gophercourier/org/v1;orgv1\xa2\x02\x03GOX\xaa\x02\x14Gophercourier.Org.V1\xca\x02\x14Gophercourier\\Org\\V1\xe2\x02 Gophercourier\\Org\\V1\\GPBMetadata\xea\x02\x16Gophercourier::Org::V1b\x06proto3"

var file_gophercourier_org_v1_org_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_gophercourier_org_v1_org_proto_goTypes = []any{
	(*Org)(nil),                    // 0: gophercourier.org.v1.Org
	(*OrgSettings)(nil),            // 1: gophercourier.org.v1.OrgSettings
	(*CreateRequest)(nil),          // 2: gophercourier.org.v1.CreateRequest
	(*CreateResponse)(nil),         // 3: gophercourier.org.v1.CreateResponse
	(*UpdateRequest)(nil),          // 4: gophercourier.org.v1.UpdateRequest
	(*UpdateResponse)(nil),         // 5: gophercourier.org.v1.UpdateResponse
	(*DeleteRequest)(nil),          // 6: gophercourier.org.v1.DeleteRequest
	(*DeleteResponse)(nil),         // 7: gophercourier.org.v1.DeleteResponse
	(*GetRequest)(nil),             // 8: gophercourier.org.v1.GetRequest
	(*GetResponse)(nil),            // 9: gophercourier.org.v1.GetResponse
	(*ListMineRequest)(nil),        // 10: gophercourier.org.v1.ListMineRequest
	(*ListMineResponse)(nil),       // 11: gophercourier.org.v1.ListMineResponse
	(*OrgWithRole)(nil),            // 12: gophercourier.org.v1.OrgWithRole
	(*ListMembersRequest)(nil),     // 13: gophercourier.org.v1.ListMembersRequest
	(*OrgMember)(nil),              // 14: gophercourier.org.v1.OrgMember
	(*ListMembersResponse)(nil),    // 15: gophercourier.org.v1.ListMembersResponse
	(*ListUsersByIDsRequest)(nil),  // 16: gophercourier.org.v1.ListUsersByIDsRequest
	(*ListUsersByIDsResponse)(nil), // 17: gophercourier.org.v1.ListUsersByIDsResponse
	(*OrgUser)(nil),                // 18: gophercourier.org.v1.OrgUser
	(*timestamppb.Timestamp)(nil),  // 19: google.protobuf.Timestamp
}
var file_gophercourier_org_v1_org_proto_depIdxs = []int32{
	1,  // 0: gophercourier.org.v1.Org.settings:type_name -> gophercourier.org.v1.OrgSettings
	19, // 1: gophercourier.org.v1.Org.created_at:type_name -> google.protobuf.Timestamp
	19, // 2: gophercourier.org.v1.Org.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: gophercourier.org.v1.CreateResponse.org:type_name -> gophercourier.org.v1.Org
	1,  // 4: gophercourier.org.v1.UpdateRequest.settings:type_name -> gophercourier.org.v1.OrgSettings
	0,  // 5: gophercourier.org.v1.UpdateResponse.org:type_name -> gophercourier.org.v1.Org
	0,  // 6: gophercourier.org.v1.GetResponse.org:type_name -> gophercourier.org.v1.Org
	12, // 7: gophercourier.org.v1.ListMineResponse.orgs:type_name -> gophercourier.org.v1.OrgWithRole
	0,  // 8: gophercourier.org.v1.OrgWithRole.org:type_name -> gophercourier.org.v1.Org
	19, // 9: gophercourier.org.v1.OrgMember.joined_at:type_name -> google.protobuf.Timestamp
	14, // 10: gophercourier.org.v1.ListMembersResponse.members:type_name -> gophercourier.org.v1.OrgMember
	18, // 11: gophercourier.org.v1.ListUsersByIDsResponse.users:type_name -> gophercourier.org.v1.OrgUser
	2,  // 12: gophercourier.org.v1.OrgService.Create:input_type -> gophercourier.org.v1.CreateRequest
	4,  // 13: gophercourier.org.v1.OrgService.Update:input_type -> gophercourier.org.v1.UpdateRequest
	6,  // 14: gophercourier.org.v1.OrgService.Delete:input_type -> gophercourier.org.v1.DeleteRequest
	8,  // 15: gophercourier.org.v1.OrgService.Get:input_type -> gophercourier.org.v1.GetRequest
	10, // 16: gophercourier.org.v1.OrgService.ListMine:input_type -> gophercourier.org.v1.ListMineRequest
	13, // 17: gophercourier.org.v1.OrgService.ListMembers:input_type -> gophercourier.org.v1.ListMembersRequest
	16, // 18: gophercourier.org.v1.OrgService.ListUsersByIDs:input_type -> gophercourier.org.v1.ListUsersByIDsRequest
	3,  // 19: gophercourier.org.v1.OrgService.Create:output_type -> gophercourier.org.v1.CreateResponse
	5,  // 20: gophercourier.org.v1.OrgService.Update:output_type -> gophercourier.org.v1.UpdateResponse
	7,  // 21: gophercourier.org.v1.OrgService.Delete:output_type -> gophercourier.org.v1.DeleteResponse
	9,  // 22: gophercourier.org.v1.OrgService.Get:output_type -> gophercourier.org.v1.GetResponse
	11, // 23: gophercourier.org.v1.OrgService.ListMine:output_type -> gophercourier.org.v1.ListMineResponse
	15, // 24: gophercourier.org.v1.OrgService.ListMembers:output_type -> gophercourier.org.v1.ListMembersResponse
	17, // 25: gophercourier.org.v1.OrgService.ListUsersByIDs:output_type -> gophercourier.org.v1.ListUsersByIDsResponse
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_gophercourier_org_v1_org_proto_init() }
func file_gophercourier_org_v1_org_proto_init() {
	if File_gophercourier_org_v1_org_proto != nil {
		return
	}
	file_gophercourier_org_v1_org_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophercourier_org_v1_org_proto_rawDesc), len(file_gophercourier_org_v1_org_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophercourier_org_v1_org_proto_goTypes,
		DependencyIndexes: file_gophercourier_org_v1_org_proto_depIdxs,
		MessageInfos:      file_gophercourier_org_v1_org_proto_msgTypes,
	}.Build()
	File_gophercourier_org_v1_org_proto = out.File
	file_gophercourier_org_v1_org_proto_goTypes = nil
	file_gophercourier_org_v1_org_proto_depIdxs = nil
}
