// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gophercourier/subscription/v1/subscription.proto

package subscriptionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetActivePlanRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetActivePlanRequest) Reset() {
	*x = GetActivePlanRequest{}
	mi := &file_gophercourier_subscription_v1_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivePlanRequest) ProtoMessage() {}

func (x *GetActivePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_subscription_v1_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetActivePlanRequest) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *GetActivePlanRequest) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

type GetActivePlanRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OrgId string
}

func (b0 GetActivePlanRequest_builder) Build() *GetActivePlanRequest {
	m0 := &GetActivePlanRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	return m0
}

type GetActivePlanResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Plan  *Plan                  `protobuf:"bytes,1,opt,name=plan,proto3"`
	xxx_hidden_Usage *Usage                 `protobuf:"bytes,2,opt,name=usage,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetActivePlanResponse) Reset() {
	*x = GetActivePlanResponse{}
	mi := &file_gophercourier_subscription_v1_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivePlanResponse) ProtoMessage() {}

func (x *GetActivePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_subscription_v1_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetActivePlanResponse) GetPlan() *Plan {
	if x != nil {
		return x.xxx_hidden_Plan
	}
	return nil
}

func (x *GetActivePlanResponse) GetUsage() *Usage {
	if x != nil {
		return x.xxx_hidden_Usage
	}
	return nil
}

func (x *GetActivePlanResponse) SetPlan(v *Plan) {
	x.xxx_hidden_Plan = v
}

func (x *GetActivePlanResponse) SetUsage(v *Usage) {
	x.xxx_hidden_Usage = v
}

func (x *GetActivePlanResponse) HasPlan() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Plan != nil
}

func (x *GetActivePlanResponse) HasUsage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Usage != nil
}

func (x *GetActivePlanResponse) ClearPlan() {
	x.xxx_hidden_Plan = nil
}

func (x *GetActivePlanResponse) ClearUsage() {
	x.xxx_hidden_Usage = nil
}

type GetActivePlanResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Plan  *Plan
	Usage *Usage
}

func (b0 GetActivePlanResponse_builder) Build() *GetActivePlanResponse {
	m0 := &GetActivePlanResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Plan = b.Plan
	x.xxx_hidden_Usage = b.Usage
	return m0
}

type Plan struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Tier               string                 `protobuf:"bytes,1,opt,name=tier,proto3"`
	xxx_hidden_Seats              int32                  `protobuf:"varint,2,opt,name=seats,proto3"`
	xxx_hidden_PlanUntil          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=plan_until,json=planUntil,proto3"`
	xxx_hidden_Features           []string               `protobuf:"bytes,4,rep,name=features,proto3"`
	xxx_hidden_Quotas             map[string]int32       `protobuf:"bytes,5,rep,name=quotas,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	xxx_hidden_InheritedFromOrgId string                 `protobuf:"bytes,6,opt,name=inherited_from_org_id,json=inheritedFromOrgId,proto3"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_gophercourier_subscription_v1_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_subscription_v1_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Plan) GetTier() string {
	if x != nil {
		return x.xxx_hidden_Tier
	}
	return ""
}

func (x *Plan) GetSeats() int32 {
	if x != nil {
		return x.xxx_hidden_Seats
	}
	return 0
}

func (x *Plan) GetPlanUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_PlanUntil
	}
	return nil
}

func (x *Plan) GetFeatures() []string {
	if x != nil {
		return x.xxx_hidden_Features
	}
	return nil
}

func (x *Plan) GetQuotas() map[string]int32 {
	if x != nil {
		return x.xxx_hidden_Quotas
	}
	return nil
}

func (x *Plan) GetInheritedFromOrgId() string {
	if x != nil {
		return x.xxx_hidden_InheritedFromOrgId
	}
	return ""
}

func (x *Plan) SetTier(v string) {
	x.xxx_hidden_Tier = v
}

func (x *Plan) SetSeats(v int32) {
	x.xxx_hidden_Seats = v
}

func (x *Plan) SetPlanUntil(v *timestamppb.Timestamp) {
	x.xxx_hidden_PlanUntil = v
}

func (x *Plan) SetFeatures(v []string) {
	x.xxx_hidden_Features = v
}

func (x *Plan) SetQuotas(v map[string]int32) {
	x.xxx_hidden_Quotas = v
}

func (x *Plan) SetInheritedFromOrgId(v string) {
	x.xxx_hidden_InheritedFromOrgId = v
}

func (x *Plan) HasPlanUntil() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PlanUntil != nil
}

func (x *Plan) ClearPlanUntil() {
	x.xxx_hidden_PlanUntil = nil
}

type Plan_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Tier      string
	Seats     int32
	PlanUntil *timestamppb.Timestamp
	Features  []string
	// org.members, org.cloud_collections, user.devices; -1 = unlimited
	Quotas             map[string]int32
	InheritedFromOrgId string
}

func (b0 Plan_builder) Build() *Plan {
	m0 := &Plan{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Tier = b.Tier
	x.xxx_hidden_Seats = b.Seats
	x.xxx_hidden_PlanUntil = b.PlanUntil
	x.xxx_hidden_Features = b.Features
	x.xxx_hidden_Quotas = b.Quotas
	x.xxx_hidden_InheritedFromOrgId = b.InheritedFromOrgId
	return m0
}

type Usage struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Members          int32                  `protobuf:"varint,1,opt,name=members,proto3"`
	xxx_hidden_PendingInvites   int32                  `protobuf:"varint,2,opt,name=pending_invites,json=pendingInvites,proto3"`
	xxx_hidden_CloudCollections int32                  `protobuf:"varint,3,opt,name=cloud_collections,json=cloudCollections,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_gophercourier_subscription_v1_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_subscription_v1_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Usage) GetMembers() int32 {
	if x != nil {
		return x.xxx_hidden_Members
	}
	return 0
}

func (x *Usage) GetPendingInvites() int32 {
	if x != nil {
		return x.xxx_hidden_PendingInvites
	}
	return 0
}

func (x *Usage) GetCloudCollections() int32 {
	if x != nil {
		return x.xxx_hidden_CloudCollections
	}
	return 0
}

func (x *Usage) SetMembers(v int32) {
	x.xxx_hidden_Members = v
}

func (x *Usage) SetPendingInvites(v int32) {
	x.xxx_hidden_PendingInvites = v
}

func (x *Usage) SetCloudCollections(v int32) {
	x.xxx_hidden_CloudCollections = v
}

type Usage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Members          int32
	PendingInvites   int32
	CloudCollections int32
}

func (b0 Usage_builder) Build() *Usage {
	m0 := &Usage{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Members = b.Members
	x.xxx_hidden_PendingInvites = b.PendingInvites
	x.xxx_hidden_CloudCollections = b.CloudCollections
	return m0
}

var File_gophercourier_subscription_v1_subscription_proto protoreflect.FileDescriptor

const file_gophercourier_subscription_v1_subscription_proto_rawDesc = "" +
	"\n" +
	"0gophercourier/subscription/v1/subscription.proto\x12\x1dgophercourier.subscription.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"-\n" +
	"\x14GetActivePlanRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"\x8c\x01\n" +
	"\x15GetActivePlanResponse\x127\n" +
	"\x04plan\x18\x01 \x01(\v2#.gophercourier.subscription.v1.PlanR\x04plan\x12:\n" +
	"\x05usage\x18\x02 \x01(\v2$.gophercourier.subscription.v1.UsageR\x05usage\"\xbe\x02\n" +
	"\x04Plan\x12\x12\n" +
	"\x04tier\x18\x01 \x01(\tR\x04tier\x12\x14\n" +
	"\x05seats\x18\x02 \x01(\x05R\x05seats\x129\n" +
	"\n" +
	"plan_until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tplanUntil\x12\x1a\n" +
	"\bfeatures\x18\x04 \x03(\tR\bfeatures\x12G\n" +
	"\x06quotas\x18\x05 \x03(\v2/.gophercourier.subscription.v1.Plan.QuotasEntryR\x06quotas\x121\n" +
	"\x15inherited_from_org_id\x18\x06 \x01(\tR\x12inheritedFromOrgId\x1a9\n" +
	"\vQuotasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"w\n" +
	"\x05Usage\x12\x18\n" +
	"\amembers\x18\x01 \x01(\x05R\amembers\x12'\n" +
	"\x0fpending_invites\x18\x02 \x01(\x05R\x0ependingInvites\x12+\n" +
	"\x11cloud_collections\x18\x03 \x01(\x05R\x10cloudCollections2\x91\x01\n" +
	"\x13SubscriptionService\x12z\n" +
	"\rGetActivePlan\x123.gophercourier.subscription.v1.GetActivePlanRequest\x1a4.gophercourier.subscription.v1.GetActivePlanResponseB\x99\x02\n" +
	"!com.gophercourier.subscription.v1B\x11SubscriptionProtoP\x01ZKgithub.com/tetiva-app/proto/go/gophercourier/subscription/v1;subscriptionv1\xa2\x02\x03GSX\xaa\x02\x1dGophercourier.Subscription.V1\xca\x02\x1dGophercourier\\Subscription\\V1\xe2\x02)Gophercourier\\Subscription\\V1\\GPBMetadata\xea\x02\x1fGophercourier::Subscription::V1b\x06proto3"

var file_gophercourier_subscription_v1_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gophercourier_subscription_v1_subscription_proto_goTypes = []any{
	(*GetActivePlanRequest)(nil),  // 0: gophercourier.subscription.v1.GetActivePlanRequest
	(*GetActivePlanResponse)(nil), // 1: gophercourier.subscription.v1.GetActivePlanResponse
	(*Plan)(nil),                  // 2: gophercourier.subscription.v1.Plan
	(*Usage)(nil),                 // 3: gophercourier.subscription.v1.Usage
	nil,                           // 4: gophercourier.subscription.v1.Plan.QuotasEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_gophercourier_subscription_v1_subscription_proto_depIdxs = []int32{
	2, // 0: gophercourier.subscription.v1.GetActivePlanResponse.plan:type_name -> gophercourier.subscription.v1.Plan
	3, // 1: gophercourier.subscription.v1.GetActivePlanResponse.usage:type_name -> gophercourier.subscription.v1.Usage
	5, // 2: gophercourier.subscription.v1.Plan.plan_until:type_name -> google.protobuf.Timestamp
	4, // 3: gophercourier.subscription.v1.Plan.quotas:type_name -> gophercourier.subscription.v1.Plan.QuotasEntry
	0, // 4: gophercourier.subscription.v1.SubscriptionService.GetActivePlan:input_type -> gophercourier.subscription.v1.GetActivePlanRequest
	1, // 5: gophercourier.subscription.v1.SubscriptionService.GetActivePlan:output_type -> gophercourier.subscription.v1.GetActivePlanResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gophercourier_subscription_v1_subscription_proto_init() }
func file_gophercourier_subscription_v1_subscription_proto_init() {
	if File_gophercourier_subscription_v1_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophercourier_subscription_v1_subscription_proto_rawDesc), len(file_gophercourier_subscription_v1_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophercourier_subscription_v1_subscription_proto_goTypes,
		DependencyIndexes: file_gophercourier_subscription_v1_subscription_proto_depIdxs,
		MessageInfos:      file_gophercourier_subscription_v1_subscription_proto_msgTypes,
	}.Build()
	File_gophercourier_subscription_v1_subscription_proto = out.File
	file_gophercourier_subscription_v1_subscription_proto_goTypes = nil
	file_gophercourier_subscription_v1_subscription_proto_depIdxs = nil
}
