// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gophercourier/role/v1/role.proto

package rolev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role is the wire shape of a domain Role entity.
type Role struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_OrgId       string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3"`
	xxx_hidden_Name        string                 `protobuf:"bytes,3,opt,name=name,proto3"`
	xxx_hidden_Description string                 `protobuf:"bytes,4,opt,name=description,proto3"`
	xxx_hidden_Scope       string                 `protobuf:"bytes,5,opt,name=scope,proto3"`
	xxx_hidden_Permissions []string               `protobuf:"bytes,6,rep,name=permissions,proto3"`
	xxx_hidden_ImplicitWs  string                 `protobuf:"bytes,7,opt,name=implicit_ws,json=implicitWs,proto3"`
	xxx_hidden_IsBuiltIn   bool                   `protobuf:"varint,8,opt,name=is_built_in,json=isBuiltIn,proto3"`
	xxx_hidden_IsDefault   bool                   `protobuf:"varint,9,opt,name=is_default,json=isDefault,proto3"`
	xxx_hidden_CreatedBy   string                 `protobuf:"bytes,10,opt,name=created_by,json=createdBy,proto3"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3"`
	xxx_hidden_Version     int32                  `protobuf:"varint,13,opt,name=version,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Role) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Role) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *Role) GetScope() string {
	if x != nil {
		return x.xxx_hidden_Scope
	}
	return ""
}

func (x *Role) GetPermissions() []string {
	if x != nil {
		return x.xxx_hidden_Permissions
	}
	return nil
}

func (x *Role) GetImplicitWs() string {
	if x != nil {
		return x.xxx_hidden_ImplicitWs
	}
	return ""
}

func (x *Role) GetIsBuiltIn() bool {
	if x != nil {
		return x.xxx_hidden_IsBuiltIn
	}
	return false
}

func (x *Role) GetIsDefault() bool {
	if x != nil {
		return x.xxx_hidden_IsDefault
	}
	return false
}

func (x *Role) GetCreatedBy() string {
	if x != nil {
		return x.xxx_hidden_CreatedBy
	}
	return ""
}

func (x *Role) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Role) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Role) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Role) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Role) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

func (x *Role) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Role) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *Role) SetScope(v string) {
	x.xxx_hidden_Scope = v
}

func (x *Role) SetPermissions(v []string) {
	x.xxx_hidden_Permissions = v
}

func (x *Role) SetImplicitWs(v string) {
	x.xxx_hidden_ImplicitWs = v
}

func (x *Role) SetIsBuiltIn(v bool) {
	x.xxx_hidden_IsBuiltIn = v
}

func (x *Role) SetIsDefault(v bool) {
	x.xxx_hidden_IsDefault = v
}

func (x *Role) SetCreatedBy(v string) {
	x.xxx_hidden_CreatedBy = v
}

func (x *Role) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Role) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Role) SetVersion(v int32) {
	x.xxx_hidden_Version = v
}

func (x *Role) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Role) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Role) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Role) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type Role_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          string
	OrgId       string
	Name        string
	Description string
	Scope       string
	Permissions []string
	ImplicitWs  string
	IsBuiltIn   bool
	IsDefault   bool
	CreatedBy   string
	CreatedAt   *timestamppb.Timestamp
	UpdatedAt   *timestamppb.Timestamp
	Version     int32
}

func (b0 Role_builder) Build() *Role {
	m0 := &Role{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_OrgId = b.OrgId
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Scope = b.Scope
	x.xxx_hidden_Permissions = b.Permissions
	x.xxx_hidden_ImplicitWs = b.ImplicitWs
	x.xxx_hidden_IsBuiltIn = b.IsBuiltIn
	x.xxx_hidden_IsDefault = b.IsDefault
	x.xxx_hidden_CreatedBy = b.CreatedBy
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	x.xxx_hidden_Version = b.Version
	return m0
}

type GetRoleRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RoleId string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRoleRequest) GetRoleId() string {
	if x != nil {
		return x.xxx_hidden_RoleId
	}
	return ""
}

func (x *GetRoleRequest) SetRoleId(v string) {
	x.xxx_hidden_RoleId = v
}

type GetRoleRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RoleId string
}

func (b0 GetRoleRequest_builder) Build() *GetRoleRequest {
	m0 := &GetRoleRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RoleId = b.RoleId
	return m0
}

type GetRoleResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Role *Role                  `protobuf:"bytes,1,opt,name=role,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRoleResponse) Reset() {
	*x = GetRoleResponse{}
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResponse) ProtoMessage() {}

func (x *GetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRoleResponse) GetRole() *Role {
	if x != nil {
		return x.xxx_hidden_Role
	}
	return nil
}

func (x *GetRoleResponse) SetRole(v *Role) {
	x.xxx_hidden_Role = v
}

func (x *GetRoleResponse) HasRole() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Role != nil
}

func (x *GetRoleResponse) ClearRole() {
	x.xxx_hidden_Role = nil
}

type GetRoleResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Role *Role
}

func (b0 GetRoleResponse_builder) Build() *GetRoleResponse {
	m0 := &GetRoleResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Role = b.Role
	return m0
}

type ListRolesRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListRolesRequest) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *ListRolesRequest) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

type ListRolesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OrgId string
}

func (b0 ListRolesRequest_builder) Build() *ListRolesRequest {
	m0 := &ListRolesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	return m0
}

type ListRolesResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Roles *[]*Role               `protobuf:"bytes,1,rep,name=roles,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListRolesResponse) GetRoles() []*Role {
	if x != nil {
		if x.xxx_hidden_Roles != nil {
			return *x.xxx_hidden_Roles
		}
	}
	return nil
}

func (x *ListRolesResponse) SetRoles(v []*Role) {
	x.xxx_hidden_Roles = &v
}

type ListRolesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Roles []*Role
}

func (b0 ListRolesResponse_builder) Build() *ListRolesResponse {
	m0 := &ListRolesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Roles = &b.Roles
	return m0
}

type CreateRoleRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId       string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	xxx_hidden_Name        string                 `protobuf:"bytes,2,opt,name=name,proto3"`
	xxx_hidden_Description string                 `protobuf:"bytes,3,opt,name=description,proto3"`
	xxx_hidden_Scope       string                 `protobuf:"bytes,4,opt,name=scope,proto3"`
	xxx_hidden_Permissions []string               `protobuf:"bytes,5,rep,name=permissions,proto3"`
	xxx_hidden_ImplicitWs  string                 `protobuf:"bytes,6,opt,name=implicit_ws,json=implicitWs,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateRoleRequest) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *CreateRoleRequest) GetScope() string {
	if x != nil {
		return x.xxx_hidden_Scope
	}
	return ""
}

func (x *CreateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.xxx_hidden_Permissions
	}
	return nil
}

func (x *CreateRoleRequest) GetImplicitWs() string {
	if x != nil {
		return x.xxx_hidden_ImplicitWs
	}
	return ""
}

func (x *CreateRoleRequest) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

func (x *CreateRoleRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *CreateRoleRequest) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *CreateRoleRequest) SetScope(v string) {
	x.xxx_hidden_Scope = v
}

func (x *CreateRoleRequest) SetPermissions(v []string) {
	x.xxx_hidden_Permissions = v
}

func (x *CreateRoleRequest) SetImplicitWs(v string) {
	x.xxx_hidden_ImplicitWs = v
}

type CreateRoleRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OrgId       string
	Name        string
	Description string
	Scope       string
	Permissions []string
	ImplicitWs  string
}

func (b0 CreateRoleRequest_builder) Build() *CreateRoleRequest {
	m0 := &CreateRoleRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Scope = b.Scope
	x.xxx_hidden_Permissions = b.Permissions
	x.xxx_hidden_ImplicitWs = b.ImplicitWs
	return m0
}

type CreateRoleResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Role *Role                  `protobuf:"bytes,1,opt,name=role,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateRoleResponse) GetRole() *Role {
	if x != nil {
		return x.xxx_hidden_Role
	}
	return nil
}

func (x *CreateRoleResponse) SetRole(v *Role) {
	x.xxx_hidden_Role = v
}

func (x *CreateRoleResponse) HasRole() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Role != nil
}

func (x *CreateRoleResponse) ClearRole() {
	x.xxx_hidden_Role = nil
}

type CreateRoleResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Role *Role
}

func (b0 CreateRoleResponse_builder) Build() *CreateRoleResponse {
	m0 := &CreateRoleResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Role = b.Role
	return m0
}

// UpdateRoleRequest uses the proto3 `optional` keyword for nullable patch
// fields. Permissions, being a repeated field, cannot be nullable in proto3 —
// the `update_permissions` boolean acts as a presence sentinel.
type UpdateRoleRequest struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RoleId            string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3"`
	xxx_hidden_OrgId             string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3"`
	xxx_hidden_Name              *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof"`
	xxx_hidden_Description       *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof"`
	xxx_hidden_Permissions       []string               `protobuf:"bytes,5,rep,name=permissions,proto3"`
	xxx_hidden_UpdatePermissions bool                   `protobuf:"varint,6,opt,name=update_permissions,json=updatePermissions,proto3"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateRoleRequest) GetRoleId() string {
	if x != nil {
		return x.xxx_hidden_RoleId
	}
	return ""
}

func (x *UpdateRoleRequest) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *UpdateRoleRequest) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *UpdateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.xxx_hidden_Permissions
	}
	return nil
}

func (x *UpdateRoleRequest) GetUpdatePermissions() bool {
	if x != nil {
		return x.xxx_hidden_UpdatePermissions
	}
	return false
}

func (x *UpdateRoleRequest) SetRoleId(v string) {
	x.xxx_hidden_RoleId = v
}

func (x *UpdateRoleRequest) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

func (x *UpdateRoleRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *UpdateRoleRequest) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *UpdateRoleRequest) SetPermissions(v []string) {
	x.xxx_hidden_Permissions = v
}

func (x *UpdateRoleRequest) SetUpdatePermissions(v bool) {
	x.xxx_hidden_UpdatePermissions = v
}

func (x *UpdateRoleRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UpdateRoleRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UpdateRoleRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Name = nil
}

func (x *UpdateRoleRequest) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Description = nil
}

type UpdateRoleRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RoleId      string
	OrgId       string
	Name        *string
	Description *string
	// permissions: ignored unless update_permissions=true. When the flag is
	// true, the entire permissions list is replaced (including with empty).
	Permissions       []string
	UpdatePermissions bool
}

func (b0 UpdateRoleRequest_builder) Build() *UpdateRoleRequest {
	m0 := &UpdateRoleRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RoleId = b.RoleId
	x.xxx_hidden_OrgId = b.OrgId
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Name = b.Name
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Description = b.Description
	}
	x.xxx_hidden_Permissions = b.Permissions
	x.xxx_hidden_UpdatePermissions = b.UpdatePermissions
	return m0
}

type UpdateRoleResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Role *Role                  `protobuf:"bytes,1,opt,name=role,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateRoleResponse) Reset() {
	*x = UpdateRoleResponse{}
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResponse) ProtoMessage() {}

func (x *UpdateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateRoleResponse) GetRole() *Role {
	if x != nil {
		return x.xxx_hidden_Role
	}
	return nil
}

func (x *UpdateRoleResponse) SetRole(v *Role) {
	x.xxx_hidden_Role = v
}

func (x *UpdateRoleResponse) HasRole() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Role != nil
}

func (x *UpdateRoleResponse) ClearRole() {
	x.xxx_hidden_Role = nil
}

type UpdateRoleResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Role *Role
}

func (b0 UpdateRoleResponse_builder) Build() *UpdateRoleResponse {
	m0 := &UpdateRoleResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Role = b.Role
	return m0
}

type DeleteRoleRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RoleId string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3"`
	xxx_hidden_OrgId  string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteRoleRequest) GetRoleId() string {
	if x != nil {
		return x.xxx_hidden_RoleId
	}
	return ""
}

func (x *DeleteRoleRequest) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *DeleteRoleRequest) SetRoleId(v string) {
	x.xxx_hidden_RoleId = v
}

func (x *DeleteRoleRequest) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

type DeleteRoleRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RoleId string
	OrgId  string
}

func (b0 DeleteRoleRequest_builder) Build() *DeleteRoleRequest {
	m0 := &DeleteRoleRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RoleId = b.RoleId
	x.xxx_hidden_OrgId = b.OrgId
	return m0
}

type DeleteRoleResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_role_v1_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteRoleResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteRoleResponse_builder) Build() *DeleteRoleResponse {
	m0 := &DeleteRoleResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_gophercourier_role_v1_role_proto protoreflect.FileDescriptor

const file_gophercourier_role_v1_role_proto_rawDesc = "" +
	"\n" +
	" gophercourier/role/v1/role.proto\x12\x15gophercourier.role.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x03\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12 \n" +
	"\vpermissions\x18\x06 \x03(\tR\vpermissions\x12\x1f\n" +
	"\vimplicit_ws\x18\a \x01(\tR\n" +
	"implicitWs\x12\x1e\n" +
	"\vis_built_in\x18\b \x01(\bR\tisBuiltIn\x12\x1d\n" +
	"\n" +
	"is_default\x18\t \x01(\bR\tisDefault\x12\x1d\n" +
	"\n" +
	"created_by\x18\n" +
	" \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\r \x01(\x05R\aversion\")\n" +
	"\x0eGetRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\"B\n" +
	"\x0fGetRoleResponse\x12/\n" +
	"\x04role\x18\x01 \x01(\v2\x1b.gophercourier.role.v1.RoleR\x04role\")\n" +
	"\x10ListRolesRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"F\n" +
	"\x11ListRolesResponse\x121\n" +
	"\x05roles\x18\x01 \x03(\v2\x1b.gophercourier.role.v1.RoleR\x05roles\"\xb9\x01\n" +
	"\x11CreateRoleRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x12\x1f\n" +
	"\vimplicit_ws\x18\x06 \x01(\tR\n" +
	"implicitWs\"E\n" +
	"\x12CreateRoleResponse\x12/\n" +
	"\x04role\x18\x01 \x01(\v2\x1b.gophercourier.role.v1.RoleR\x04role\"\xed\x01\n" +
	"\x11UpdateRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x12-\n" +
	"\x12update_permissions\x18\x06 \x01(\bR\x11updatePermissionsB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"E\n" +
	"\x12UpdateRoleResponse\x12/\n" +
	"\x04role\x18\x01 \x01(\v2\x1b.gophercourier.role.v1.RoleR\x04role\"C\n" +
	"\x11DeleteRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\"\x14\n" +
	"\x12DeleteRoleResponse2\xf0\x03\n" +
	"\vRoleService\x12X\n" +
	"\aGetRole\x12%.gophercourier.role.v1.GetRoleRequest\x1a&.gophercourier.role.v1.GetRoleResponse\x12^\n" +
	"\tListRoles\x12'.gophercourier.role.v1.ListRolesRequest\x1a(.gophercourier.role.v1.ListRolesResponse\x12a\n" +
	"\n" +
	"CreateRole\x12(.gophercourier.role.v1.CreateRoleRequest\x1a).gophercourier.role.v1.CreateRoleResponse\x12a\n" +
	"\n" +
	"UpdateRole\x12(.gophercourier.role.v1.UpdateRoleRequest\x1a).gophercourier.role.v1.UpdateRoleResponse\x12a\n" +
	"\n" +
	"DeleteRole\x12(.gophercourier.role.v1.DeleteRoleRequest\x1a).gophercourier.role.v1.DeleteRoleResponseB\xd9\x01\n" +
	"\x19com.gophercourier.role.v1B\tRoleProtoP\x01Z;github.com/tetiva-app/proto/go/gophercourier/role/v1;rolev1\xa2\x02\x03GRX\xaa\x02\x15Gophercourier.Role.V1\xca\x02\x15Gophercourier\\Role\\V1\xe2\x02!Gophercourier\\Role\\V1\\GPBMetadata\xea\x02\x17Gophercourier::Role::V1b\x06proto3"

var file_gophercourier_role_v1_role_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_gophercourier_role_v1_role_proto_goTypes = []any{
	(*Role)(nil),                  // 0: gophercourier.role.v1.Role
	(*GetRoleRequest)(nil),        // 1: gophercourier.role.v1.GetRoleRequest
	(*GetRoleResponse)(nil),       // 2: gophercourier.role.v1.GetRoleResponse
	(*ListRolesRequest)(nil),      // 3: gophercourier.role.v1.ListRolesRequest
	(*ListRolesResponse)(nil),     // 4: gophercourier.role.v1.ListRolesResponse
	(*CreateRoleRequest)(nil),     // 5: gophercourier.role.v1.CreateRoleRequest
	(*CreateRoleResponse)(nil),    // 6: gophercourier.role.v1.CreateRoleResponse
	(*UpdateRoleRequest)(nil),     // 7: gophercourier.role.v1.UpdateRoleRequest
	(*UpdateRoleResponse)(nil),    // 8: gophercourier.role.v1.UpdateRoleResponse
	(*DeleteRoleRequest)(nil),     // 9: gophercourier.role.v1.DeleteRoleRequest
	(*DeleteRoleResponse)(nil),    // 10: gophercourier.role.v1.DeleteRoleResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_gophercourier_role_v1_role_proto_depIdxs = []int32{
	11, // 0: gophercourier.role.v1.Role.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: gophercourier.role.v1.Role.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: gophercourier.role.v1.GetRoleResponse.role:type_name -> gophercourier.role.v1.Role
	0,  // 3: gophercourier.role.v1.ListRolesResponse.roles:type_name -> gophercourier.role.v1.Role
	0,  // 4: gophercourier.role.v1.CreateRoleResponse.role:type_name -> gophercourier.role.v1.Role
	0,  // 5: gophercourier.role.v1.UpdateRoleResponse.role:type_name -> gophercourier.role.v1.Role
	1,  // 6: gophercourier.role.v1.RoleService.GetRole:input_type -> gophercourier.role.v1.GetRoleRequest
	3,  // 7: gophercourier.role.v1.RoleService.ListRoles:input_type -> gophercourier.role.v1.ListRolesRequest
	5,  // 8: gophercourier.role.v1.RoleService.CreateRole:input_type -> gophercourier.role.v1.CreateRoleRequest
	7,  // 9: gophercourier.role.v1.RoleService.UpdateRole:input_type -> gophercourier.role.v1.UpdateRoleRequest
	9,  // 10: gophercourier.role.v1.RoleService.DeleteRole:input_type -> gophercourier.role.v1.DeleteRoleRequest
	2,  // 11: gophercourier.role.v1.RoleService.GetRole:output_type -> gophercourier.role.v1.GetRoleResponse
	4,  // 12: gophercourier.role.v1.RoleService.ListRoles:output_type -> gophercourier.role.v1.ListRolesResponse
	6,  // 13: gophercourier.role.v1.RoleService.CreateRole:output_type -> gophercourier.role.v1.CreateRoleResponse
	8,  // 14: gophercourier.role.v1.RoleService.UpdateRole:output_type -> gophercourier.role.v1.UpdateRoleResponse
	10, // 15: gophercourier.role.v1.RoleService.DeleteRole:output_type -> gophercourier.role.v1.DeleteRoleResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_gophercourier_role_v1_role_proto_init() }
func file_gophercourier_role_v1_role_proto_init() {
	if File_gophercourier_role_v1_role_proto != nil {
		return
	}
	file_gophercourier_role_v1_role_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophercourier_role_v1_role_proto_rawDesc), len(file_gophercourier_role_v1_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophercourier_role_v1_role_proto_goTypes,
		DependencyIndexes: file_gophercourier_role_v1_role_proto_depIdxs,
		MessageInfos:      file_gophercourier_role_v1_role_proto_msgTypes,
	}.Build()
	File_gophercourier_role_v1_role_proto = out.File
	file_gophercourier_role_v1_role_proto_goTypes = nil
	file_gophercourier_role_v1_role_proto_depIdxs = nil
}
