// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: gophercourier/platform/v1/platform.proto

package platformv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlatformService_ListOrgs_FullMethodName            = "/gophercourier.platform.v1.PlatformService/ListOrgs"
	PlatformService_GetOrg_FullMethodName              = "/gophercourier.platform.v1.PlatformService/GetOrg"
	PlatformService_ListUsers_FullMethodName           = "/gophercourier.platform.v1.PlatformService/ListUsers"
	PlatformService_GetUser_FullMethodName             = "/gophercourier.platform.v1.PlatformService/GetUser"
	PlatformService_ListAudit_FullMethodName           = "/gophercourier.platform.v1.PlatformService/ListAudit"
	PlatformService_ForceResetPassword_FullMethodName  = "/gophercourier.platform.v1.PlatformService/ForceResetPassword"
	PlatformService_ForceTransferOrg_FullMethodName    = "/gophercourier.platform.v1.PlatformService/ForceTransferOrg"
	PlatformService_ForceRevokeSessions_FullMethodName = "/gophercourier.platform.v1.PlatformService/ForceRevokeSessions"
	PlatformService_ForceDeleteUser_FullMethodName     = "/gophercourier.platform.v1.PlatformService/ForceDeleteUser"
	PlatformService_ForceDeleteOrg_FullMethodName      = "/gophercourier.platform.v1.PlatformService/ForceDeleteOrg"
	PlatformService_AdminVerifyEmail_FullMethodName    = "/gophercourier.platform.v1.PlatformService/AdminVerifyEmail"
	PlatformService_SetPlan_FullMethodName             = "/gophercourier.platform.v1.PlatformService/SetPlan"
)

// PlatformServiceClient is the client API for PlatformService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PlatformService is the Platform Admin (Instance Operator) gRPC surface.
// Combines read-only support API with tightly-bounded force-* mutations.
//
// Per spec [07] + [12] §M11:
//   - Every method requires the caller's JWT to carry IsPlatformStaff=true
//     (enforced by PlatformStaffGuard interceptor).
//   - Every read emits a `platform.read` audit row server-side.
//   - Every force-* mutation requires `Reason` (10..500 chars after trim) and
//     emits a matching `platform.*` audit row PLUS cascaded
//     `auth.session_revoked` per killed session.
type PlatformServiceClient interface {
	// Read.
	ListOrgs(ctx context.Context, in *PlatformServiceListOrgsRequest, opts ...grpc.CallOption) (*PlatformServiceListOrgsResponse, error)
	GetOrg(ctx context.Context, in *PlatformServiceGetOrgRequest, opts ...grpc.CallOption) (*PlatformServiceGetOrgResponse, error)
	ListUsers(ctx context.Context, in *PlatformServiceListUsersRequest, opts ...grpc.CallOption) (*PlatformServiceListUsersResponse, error)
	GetUser(ctx context.Context, in *PlatformServiceGetUserRequest, opts ...grpc.CallOption) (*PlatformServiceGetUserResponse, error)
	ListAudit(ctx context.Context, in *PlatformServiceListAuditRequest, opts ...grpc.CallOption) (*PlatformServiceListAuditResponse, error)
	// Write (force-*).
	ForceResetPassword(ctx context.Context, in *PlatformServiceForceResetPasswordRequest, opts ...grpc.CallOption) (*PlatformServiceForceResetPasswordResponse, error)
	ForceTransferOrg(ctx context.Context, in *PlatformServiceForceTransferOrgRequest, opts ...grpc.CallOption) (*PlatformServiceForceTransferOrgResponse, error)
	ForceRevokeSessions(ctx context.Context, in *PlatformServiceForceRevokeSessionsRequest, opts ...grpc.CallOption) (*PlatformServiceForceRevokeSessionsResponse, error)
	ForceDeleteUser(ctx context.Context, in *PlatformServiceForceDeleteUserRequest, opts ...grpc.CallOption) (*PlatformServiceForceDeleteUserResponse, error)
	// ForceDeleteOrg soft-deletes a non-personal org with cascade. Personal orgs
	// are rejected with FailedPrecondition. Reason is required (10..500 chars).
	ForceDeleteOrg(ctx context.Context, in *PlatformServiceForceDeleteOrgRequest, opts ...grpc.CallOption) (*PlatformServiceForceDeleteOrgResponse, error)
	// AdminVerifyEmail flips email_verified=true without involving the user's
	// verification-email flow. Idempotent — already-verified users return
	// was_already_verified=true without error.
	AdminVerifyEmail(ctx context.Context, in *PlatformServiceAdminVerifyEmailRequest, opts ...grpc.CallOption) (*PlatformServiceAdminVerifyEmailResponse, error)
	// SetPlan assigns a billing plan to an org. Both upgrade and downgrade go
	// through this single call; nothing is deleted on downgrade.
	SetPlan(ctx context.Context, in *PlatformServiceSetPlanRequest, opts ...grpc.CallOption) (*PlatformServiceSetPlanResponse, error)
}

type platformServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformServiceClient(cc grpc.ClientConnInterface) PlatformServiceClient {
	return &platformServiceClient{cc}
}

func (c *platformServiceClient) ListOrgs(ctx context.Context, in *PlatformServiceListOrgsRequest, opts ...grpc.CallOption) (*PlatformServiceListOrgsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformServiceListOrgsResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListOrgs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) GetOrg(ctx context.Context, in *PlatformServiceGetOrgRequest, opts ...grpc.CallOption) (*PlatformServiceGetOrgResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformServiceGetOrgResponse)
	err := c.cc.Invoke(ctx, PlatformService_GetOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ListUsers(ctx context.Context, in *PlatformServiceListUsersRequest, opts ...grpc.CallOption) (*PlatformServiceListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformServiceListUsersResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) GetUser(ctx context.Context, in *PlatformServiceGetUserRequest, opts ...grpc.CallOption) (*PlatformServiceGetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformServiceGetUserResponse)
	err := c.cc.Invoke(ctx, PlatformService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ListAudit(ctx context.Context, in *PlatformServiceListAuditRequest, opts ...grpc.CallOption) (*PlatformServiceListAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformServiceListAuditResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ForceResetPassword(ctx context.Context, in *PlatformServiceForceResetPasswordRequest, opts ...grpc.CallOption) (*PlatformServiceForceResetPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformServiceForceResetPasswordResponse)
	err := c.cc.Invoke(ctx, PlatformService_ForceResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ForceTransferOrg(ctx context.Context, in *PlatformServiceForceTransferOrgRequest, opts ...grpc.CallOption) (*PlatformServiceForceTransferOrgResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformServiceForceTransferOrgResponse)
	err := c.cc.Invoke(ctx, PlatformService_ForceTransferOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ForceRevokeSessions(ctx context.Context, in *PlatformServiceForceRevokeSessionsRequest, opts ...grpc.CallOption) (*PlatformServiceForceRevokeSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformServiceForceRevokeSessionsResponse)
	err := c.cc.Invoke(ctx, PlatformService_ForceRevokeSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ForceDeleteUser(ctx context.Context, in *PlatformServiceForceDeleteUserRequest, opts ...grpc.CallOption) (*PlatformServiceForceDeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformServiceForceDeleteUserResponse)
	err := c.cc.Invoke(ctx, PlatformService_ForceDeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ForceDeleteOrg(ctx context.Context, in *PlatformServiceForceDeleteOrgRequest, opts ...grpc.CallOption) (*PlatformServiceForceDeleteOrgResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformServiceForceDeleteOrgResponse)
	err := c.cc.Invoke(ctx, PlatformService_ForceDeleteOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) AdminVerifyEmail(ctx context.Context, in *PlatformServiceAdminVerifyEmailRequest, opts ...grpc.CallOption) (*PlatformServiceAdminVerifyEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformServiceAdminVerifyEmailResponse)
	err := c.cc.Invoke(ctx, PlatformService_AdminVerifyEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) SetPlan(ctx context.Context, in *PlatformServiceSetPlanRequest, opts ...grpc.CallOption) (*PlatformServiceSetPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformServiceSetPlanResponse)
	err := c.cc.Invoke(ctx, PlatformService_SetPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformServiceServer is the server API for PlatformService service.
// All implementations must embed UnimplementedPlatformServiceServer
// for forward compatibility.
//
// PlatformService is the Platform Admin (Instance Operator) gRPC surface.
// Combines read-only support API with tightly-bounded force-* mutations.
//
// Per spec [07] + [12] §M11:
//   - Every method requires the caller's JWT to carry IsPlatformStaff=true
//     (enforced by PlatformStaffGuard interceptor).
//   - Every read emits a `platform.read` audit row server-side.
//   - Every force-* mutation requires `Reason` (10..500 chars after trim) and
//     emits a matching `platform.*` audit row PLUS cascaded
//     `auth.session_revoked` per killed session.
type PlatformServiceServer interface {
	// Read.
	ListOrgs(context.Context, *PlatformServiceListOrgsRequest) (*PlatformServiceListOrgsResponse, error)
	GetOrg(context.Context, *PlatformServiceGetOrgRequest) (*PlatformServiceGetOrgResponse, error)
	ListUsers(context.Context, *PlatformServiceListUsersRequest) (*PlatformServiceListUsersResponse, error)
	GetUser(context.Context, *PlatformServiceGetUserRequest) (*PlatformServiceGetUserResponse, error)
	ListAudit(context.Context, *PlatformServiceListAuditRequest) (*PlatformServiceListAuditResponse, error)
	// Write (force-*).
	ForceResetPassword(context.Context, *PlatformServiceForceResetPasswordRequest) (*PlatformServiceForceResetPasswordResponse, error)
	ForceTransferOrg(context.Context, *PlatformServiceForceTransferOrgRequest) (*PlatformServiceForceTransferOrgResponse, error)
	ForceRevokeSessions(context.Context, *PlatformServiceForceRevokeSessionsRequest) (*PlatformServiceForceRevokeSessionsResponse, error)
	ForceDeleteUser(context.Context, *PlatformServiceForceDeleteUserRequest) (*PlatformServiceForceDeleteUserResponse, error)
	// ForceDeleteOrg soft-deletes a non-personal org with cascade. Personal orgs
	// are rejected with FailedPrecondition. Reason is required (10..500 chars).
	ForceDeleteOrg(context.Context, *PlatformServiceForceDeleteOrgRequest) (*PlatformServiceForceDeleteOrgResponse, error)
	// AdminVerifyEmail flips email_verified=true without involving the user's
	// verification-email flow. Idempotent — already-verified users return
	// was_already_verified=true without error.
	AdminVerifyEmail(context.Context, *PlatformServiceAdminVerifyEmailRequest) (*PlatformServiceAdminVerifyEmailResponse, error)
	// SetPlan assigns a billing plan to an org. Both upgrade and downgrade go
	// through this single call; nothing is deleted on downgrade.
	SetPlan(context.Context, *PlatformServiceSetPlanRequest) (*PlatformServiceSetPlanResponse, error)
	mustEmbedUnimplementedPlatformServiceServer()
}

// UnimplementedPlatformServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlatformServiceServer struct{}

func (UnimplementedPlatformServiceServer) ListOrgs(context.Context, *PlatformServiceListOrgsRequest) (*PlatformServiceListOrgsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrgs not implemented")
}
func (UnimplementedPlatformServiceServer) GetOrg(context.Context, *PlatformServiceGetOrgRequest) (*PlatformServiceGetOrgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrg not implemented")
}
func (UnimplementedPlatformServiceServer) ListUsers(context.Context, *PlatformServiceListUsersRequest) (*PlatformServiceListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedPlatformServiceServer) GetUser(context.Context, *PlatformServiceGetUserRequest) (*PlatformServiceGetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedPlatformServiceServer) ListAudit(context.Context, *PlatformServiceListAuditRequest) (*PlatformServiceListAuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAudit not implemented")
}
func (UnimplementedPlatformServiceServer) ForceResetPassword(context.Context, *PlatformServiceForceResetPasswordRequest) (*PlatformServiceForceResetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForceResetPassword not implemented")
}
func (UnimplementedPlatformServiceServer) ForceTransferOrg(context.Context, *PlatformServiceForceTransferOrgRequest) (*PlatformServiceForceTransferOrgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForceTransferOrg not implemented")
}
func (UnimplementedPlatformServiceServer) ForceRevokeSessions(context.Context, *PlatformServiceForceRevokeSessionsRequest) (*PlatformServiceForceRevokeSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForceRevokeSessions not implemented")
}
func (UnimplementedPlatformServiceServer) ForceDeleteUser(context.Context, *PlatformServiceForceDeleteUserRequest) (*PlatformServiceForceDeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForceDeleteUser not implemented")
}
func (UnimplementedPlatformServiceServer) ForceDeleteOrg(context.Context, *PlatformServiceForceDeleteOrgRequest) (*PlatformServiceForceDeleteOrgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForceDeleteOrg not implemented")
}
func (UnimplementedPlatformServiceServer) AdminVerifyEmail(context.Context, *PlatformServiceAdminVerifyEmailRequest) (*PlatformServiceAdminVerifyEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminVerifyEmail not implemented")
}
func (UnimplementedPlatformServiceServer) SetPlan(context.Context, *PlatformServiceSetPlanRequest) (*PlatformServiceSetPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPlan not implemented")
}
func (UnimplementedPlatformServiceServer) mustEmbedUnimplementedPlatformServiceServer() {}
func (UnimplementedPlatformServiceServer) testEmbeddedByValue()                         {}

// UnsafePlatformServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformServiceServer will
// result in compilation errors.
type UnsafePlatformServiceServer interface {
	mustEmbedUnimplementedPlatformServiceServer()
}

func RegisterPlatformServiceServer(s grpc.ServiceRegistrar, srv PlatformServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlatformServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlatformService_ServiceDesc, srv)
}

func _PlatformService_ListOrgs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformServiceListOrgsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListOrgs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListOrgs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListOrgs(ctx, req.(*PlatformServiceListOrgsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_GetOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformServiceGetOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).GetOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_GetOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).GetOrg(ctx, req.(*PlatformServiceGetOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformServiceListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListUsers(ctx, req.(*PlatformServiceListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformServiceGetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).GetUser(ctx, req.(*PlatformServiceGetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ListAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformServiceListAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListAudit(ctx, req.(*PlatformServiceListAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ForceResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformServiceForceResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ForceResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ForceResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ForceResetPassword(ctx, req.(*PlatformServiceForceResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ForceTransferOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformServiceForceTransferOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ForceTransferOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ForceTransferOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ForceTransferOrg(ctx, req.(*PlatformServiceForceTransferOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ForceRevokeSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformServiceForceRevokeSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ForceRevokeSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ForceRevokeSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ForceRevokeSessions(ctx, req.(*PlatformServiceForceRevokeSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ForceDeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformServiceForceDeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ForceDeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ForceDeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ForceDeleteUser(ctx, req.(*PlatformServiceForceDeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ForceDeleteOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformServiceForceDeleteOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ForceDeleteOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ForceDeleteOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ForceDeleteOrg(ctx, req.(*PlatformServiceForceDeleteOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_AdminVerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformServiceAdminVerifyEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).AdminVerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_AdminVerifyEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).AdminVerifyEmail(ctx, req.(*PlatformServiceAdminVerifyEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_SetPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformServiceSetPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).SetPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_SetPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).SetPlan(ctx, req.(*PlatformServiceSetPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlatformService_ServiceDesc is the grpc.ServiceDesc for PlatformService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlatformService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gophercourier.platform.v1.PlatformService",
	HandlerType: (*PlatformServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOrgs",
			Handler:    _PlatformService_ListOrgs_Handler,
		},
		{
			MethodName: "GetOrg",
			Handler:    _PlatformService_GetOrg_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _PlatformService_ListUsers_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _PlatformService_GetUser_Handler,
		},
		{
			MethodName: "ListAudit",
			Handler:    _PlatformService_ListAudit_Handler,
		},
		{
			MethodName: "ForceResetPassword",
			Handler:    _PlatformService_ForceResetPassword_Handler,
		},
		{
			MethodName: "ForceTransferOrg",
			Handler:    _PlatformService_ForceTransferOrg_Handler,
		},
		{
			MethodName: "ForceRevokeSessions",
			Handler:    _PlatformService_ForceRevokeSessions_Handler,
		},
		{
			MethodName: "ForceDeleteUser",
			Handler:    _PlatformService_ForceDeleteUser_Handler,
		},
		{
			MethodName: "ForceDeleteOrg",
			Handler:    _PlatformService_ForceDeleteOrg_Handler,
		},
		{
			MethodName: "AdminVerifyEmail",
			Handler:    _PlatformService_AdminVerifyEmail_Handler,
		},
		{
			MethodName: "SetPlan",
			Handler:    _PlatformService_SetPlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gophercourier/platform/v1/platform.proto",
}
