// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gophercourier/billing/v1/billing.proto

package billingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId          string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	xxx_hidden_Tier           string                 `protobuf:"bytes,2,opt,name=tier,proto3"`
	xxx_hidden_Period         string                 `protobuf:"bytes,3,opt,name=period,proto3"`
	xxx_hidden_IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_gophercourier_billing_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_billing_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SubscribeRequest) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *SubscribeRequest) GetTier() string {
	if x != nil {
		return x.xxx_hidden_Tier
	}
	return ""
}

func (x *SubscribeRequest) GetPeriod() string {
	if x != nil {
		return x.xxx_hidden_Period
	}
	return ""
}

func (x *SubscribeRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.xxx_hidden_IdempotencyKey
	}
	return ""
}

func (x *SubscribeRequest) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

func (x *SubscribeRequest) SetTier(v string) {
	x.xxx_hidden_Tier = v
}

func (x *SubscribeRequest) SetPeriod(v string) {
	x.xxx_hidden_Period = v
}

func (x *SubscribeRequest) SetIdempotencyKey(v string) {
	x.xxx_hidden_IdempotencyKey = v
}

type SubscribeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OrgId  string
	Tier   string
	Period string
	// Client-generated UUID, stable across retries of the same intent. The
	// server derives the payment id from it, so a repeated click reuses the
	// existing checkout instead of opening a second one.
	IdempotencyKey string
}

func (b0 SubscribeRequest_builder) Build() *SubscribeRequest {
	m0 := &SubscribeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	x.xxx_hidden_Tier = b.Tier
	x.xxx_hidden_Period = b.Period
	x.xxx_hidden_IdempotencyKey = b.IdempotencyKey
	return m0
}

type SubscribeResponse struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PaymentId       string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3"`
	xxx_hidden_ConfirmationUrl string                 `protobuf:"bytes,2,opt,name=confirmation_url,json=confirmationUrl,proto3"`
	xxx_hidden_AmountMinor     int64                  `protobuf:"varint,3,opt,name=amount_minor,json=amountMinor,proto3"`
	xxx_hidden_Currency        string                 `protobuf:"bytes,4,opt,name=currency,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_gophercourier_billing_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_billing_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SubscribeResponse) GetPaymentId() string {
	if x != nil {
		return x.xxx_hidden_PaymentId
	}
	return ""
}

func (x *SubscribeResponse) GetConfirmationUrl() string {
	if x != nil {
		return x.xxx_hidden_ConfirmationUrl
	}
	return ""
}

func (x *SubscribeResponse) GetAmountMinor() int64 {
	if x != nil {
		return x.xxx_hidden_AmountMinor
	}
	return 0
}

func (x *SubscribeResponse) GetCurrency() string {
	if x != nil {
		return x.xxx_hidden_Currency
	}
	return ""
}

func (x *SubscribeResponse) SetPaymentId(v string) {
	x.xxx_hidden_PaymentId = v
}

func (x *SubscribeResponse) SetConfirmationUrl(v string) {
	x.xxx_hidden_ConfirmationUrl = v
}

func (x *SubscribeResponse) SetAmountMinor(v int64) {
	x.xxx_hidden_AmountMinor = v
}

func (x *SubscribeResponse) SetCurrency(v string) {
	x.xxx_hidden_Currency = v
}

type SubscribeResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PaymentId       string
	ConfirmationUrl string
	AmountMinor     int64
	Currency        string
}

func (b0 SubscribeResponse_builder) Build() *SubscribeResponse {
	m0 := &SubscribeResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PaymentId = b.PaymentId
	x.xxx_hidden_ConfirmationUrl = b.ConfirmationUrl
	x.xxx_hidden_AmountMinor = b.AmountMinor
	x.xxx_hidden_Currency = b.Currency
	return m0
}

type GetPaymentStatusRequest struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PaymentId string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetPaymentStatusRequest) Reset() {
	*x = GetPaymentStatusRequest{}
	mi := &file_gophercourier_billing_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusRequest) ProtoMessage() {}

func (x *GetPaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_billing_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetPaymentStatusRequest) GetPaymentId() string {
	if x != nil {
		return x.xxx_hidden_PaymentId
	}
	return ""
}

func (x *GetPaymentStatusRequest) SetPaymentId(v string) {
	x.xxx_hidden_PaymentId = v
}

type GetPaymentStatusRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PaymentId string
}

func (b0 GetPaymentStatusRequest_builder) Build() *GetPaymentStatusRequest {
	m0 := &GetPaymentStatusRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PaymentId = b.PaymentId
	return m0
}

type GetPaymentStatusResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PaymentId    string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3"`
	xxx_hidden_Status       string                 `protobuf:"bytes,2,opt,name=status,proto3"`
	xxx_hidden_CancelReason string                 `protobuf:"bytes,3,opt,name=cancel_reason,json=cancelReason,proto3"`
	xxx_hidden_Subscription *Subscription          `protobuf:"bytes,4,opt,name=subscription,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetPaymentStatusResponse) Reset() {
	*x = GetPaymentStatusResponse{}
	mi := &file_gophercourier_billing_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusResponse) ProtoMessage() {}

func (x *GetPaymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_billing_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetPaymentStatusResponse) GetPaymentId() string {
	if x != nil {
		return x.xxx_hidden_PaymentId
	}
	return ""
}

func (x *GetPaymentStatusResponse) GetStatus() string {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return ""
}

func (x *GetPaymentStatusResponse) GetCancelReason() string {
	if x != nil {
		return x.xxx_hidden_CancelReason
	}
	return ""
}

func (x *GetPaymentStatusResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.xxx_hidden_Subscription
	}
	return nil
}

func (x *GetPaymentStatusResponse) SetPaymentId(v string) {
	x.xxx_hidden_PaymentId = v
}

func (x *GetPaymentStatusResponse) SetStatus(v string) {
	x.xxx_hidden_Status = v
}

func (x *GetPaymentStatusResponse) SetCancelReason(v string) {
	x.xxx_hidden_CancelReason = v
}

func (x *GetPaymentStatusResponse) SetSubscription(v *Subscription) {
	x.xxx_hidden_Subscription = v
}

func (x *GetPaymentStatusResponse) HasSubscription() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Subscription != nil
}

func (x *GetPaymentStatusResponse) ClearSubscription() {
	x.xxx_hidden_Subscription = nil
}

type GetPaymentStatusResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PaymentId    string
	Status       string
	CancelReason string
	Subscription *Subscription
}

func (b0 GetPaymentStatusResponse_builder) Build() *GetPaymentStatusResponse {
	m0 := &GetPaymentStatusResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PaymentId = b.PaymentId
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_CancelReason = b.CancelReason
	x.xxx_hidden_Subscription = b.Subscription
	return m0
}

type GetSubscriptionRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	mi := &file_gophercourier_billing_v1_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_billing_v1_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSubscriptionRequest) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *GetSubscriptionRequest) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

type GetSubscriptionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OrgId string
}

func (b0 GetSubscriptionRequest_builder) Build() *GetSubscriptionRequest {
	m0 := &GetSubscriptionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	return m0
}

type GetSubscriptionResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Subscription *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetSubscriptionResponse) Reset() {
	*x = GetSubscriptionResponse{}
	mi := &file_gophercourier_billing_v1_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionResponse) ProtoMessage() {}

func (x *GetSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_billing_v1_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.xxx_hidden_Subscription
	}
	return nil
}

func (x *GetSubscriptionResponse) SetSubscription(v *Subscription) {
	x.xxx_hidden_Subscription = v
}

func (x *GetSubscriptionResponse) HasSubscription() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Subscription != nil
}

func (x *GetSubscriptionResponse) ClearSubscription() {
	x.xxx_hidden_Subscription = nil
}

type GetSubscriptionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Subscription *Subscription
}

func (b0 GetSubscriptionResponse_builder) Build() *GetSubscriptionResponse {
	m0 := &GetSubscriptionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Subscription = b.Subscription
	return m0
}

type Subscription struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id               string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Tier             string                 `protobuf:"bytes,2,opt,name=tier,proto3"`
	xxx_hidden_Period           string                 `protobuf:"bytes,3,opt,name=period,proto3"`
	xxx_hidden_Seats            int32                  `protobuf:"varint,4,opt,name=seats,proto3"`
	xxx_hidden_Status           string                 `protobuf:"bytes,5,opt,name=status,proto3"`
	xxx_hidden_CurrentPeriodEnd *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=current_period_end,json=currentPeriodEnd,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_gophercourier_billing_v1_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_billing_v1_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Subscription) GetTier() string {
	if x != nil {
		return x.xxx_hidden_Tier
	}
	return ""
}

func (x *Subscription) GetPeriod() string {
	if x != nil {
		return x.xxx_hidden_Period
	}
	return ""
}

func (x *Subscription) GetSeats() int32 {
	if x != nil {
		return x.xxx_hidden_Seats
	}
	return 0
}

func (x *Subscription) GetStatus() string {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return ""
}

func (x *Subscription) GetCurrentPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CurrentPeriodEnd
	}
	return nil
}

func (x *Subscription) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Subscription) SetTier(v string) {
	x.xxx_hidden_Tier = v
}

func (x *Subscription) SetPeriod(v string) {
	x.xxx_hidden_Period = v
}

func (x *Subscription) SetSeats(v int32) {
	x.xxx_hidden_Seats = v
}

func (x *Subscription) SetStatus(v string) {
	x.xxx_hidden_Status = v
}

func (x *Subscription) SetCurrentPeriodEnd(v *timestamppb.Timestamp) {
	x.xxx_hidden_CurrentPeriodEnd = v
}

func (x *Subscription) HasCurrentPeriodEnd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CurrentPeriodEnd != nil
}

func (x *Subscription) ClearCurrentPeriodEnd() {
	x.xxx_hidden_CurrentPeriodEnd = nil
}

type Subscription_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id               string
	Tier             string
	Period           string
	Seats            int32
	Status           string
	CurrentPeriodEnd *timestamppb.Timestamp
}

func (b0 Subscription_builder) Build() *Subscription {
	m0 := &Subscription{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Tier = b.Tier
	x.xxx_hidden_Period = b.Period
	x.xxx_hidden_Seats = b.Seats
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_CurrentPeriodEnd = b.CurrentPeriodEnd
	return m0
}

var File_gophercourier_billing_v1_billing_proto protoreflect.FileDescriptor

const file_gophercourier_billing_v1_billing_proto_rawDesc = "" +
	"\n" +
	"&gophercourier/billing/v1/billing.proto\x12\x18gophercourier.billing.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"~\n" +
	"\x10SubscribeRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\tR\x04tier\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"\x9c\x01\n" +
	"\x11SubscribeResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12)\n" +
	"\x10confirmation_url\x18\x02 \x01(\tR\x0fconfirmationUrl\x12!\n" +
	"\famount_minor\x18\x03 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"8\n" +
	"\x17GetPaymentStatusRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"\xc2\x01\n" +
	"\x18GetPaymentStatusResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rcancel_reason\x18\x03 \x01(\tR\fcancelReason\x12J\n" +
	"\fsubscription\x18\x04 \x01(\v2&.gophercourier.billing.v1.SubscriptionR\fsubscription\"/\n" +
	"\x16GetSubscriptionRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"e\n" +
	"\x17GetSubscriptionResponse\x12J\n" +
	"\fsubscription\x18\x01 \x01(\v2&.gophercourier.billing.v1.SubscriptionR\fsubscription\"\xc2\x01\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\tR\x04tier\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\x12\x14\n" +
	"\x05seats\x18\x04 \x01(\x05R\x05seats\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12H\n" +
	"\x12current_period_end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x10currentPeriodEnd2\xe9\x02\n" +
	"\x0eBillingService\x12d\n" +
	"\tSubscribe\x12*.gophercourier.billing.v1.SubscribeRequest\x1a+.gophercourier.billing.v1.SubscribeResponse\x12y\n" +
	"\x10GetPaymentStatus\x121.gophercourier.billing.v1.GetPaymentStatusRequest\x1a2.gophercourier.billing.v1.GetPaymentStatusResponse\x12v\n" +
	"\x0fGetSubscription\x120.gophercourier.billing.v1.GetSubscriptionRequest\x1a1.gophercourier.billing.v1.GetSubscriptionResponseB\xf1\x01\n" +
	"\x1ccom.gophercourier.billing.v1B\fBillingProtoP\x01ZAgithub.com/tetiva-app/proto/go/gophercourier/billing/v1;billingv1\xa2\x02\x03GBX\xaa\x02\x18Gophercourier.Billing.V1\xca\x02\x18Gophercourier\\Billing\\V1\xe2\x02$Gophercourier\\Billing\\V1\\GPBMetadata\xea\x02\x1aGophercourier::Billing::V1b\x06proto3"

var file_gophercourier_billing_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gophercourier_billing_v1_billing_proto_goTypes = []any{
	(*SubscribeRequest)(nil),         // 0: gophercourier.billing.v1.SubscribeRequest
	(*SubscribeResponse)(nil),        // 1: gophercourier.billing.v1.SubscribeResponse
	(*GetPaymentStatusRequest)(nil),  // 2: gophercourier.billing.v1.GetPaymentStatusRequest
	(*GetPaymentStatusResponse)(nil), // 3: gophercourier.billing.v1.GetPaymentStatusResponse
	(*GetSubscriptionRequest)(nil),   // 4: gophercourier.billing.v1.GetSubscriptionRequest
	(*GetSubscriptionResponse)(nil),  // 5: gophercourier.billing.v1.GetSubscriptionResponse
	(*Subscription)(nil),             // 6: gophercourier.billing.v1.Subscription
	(*timestamppb.Timestamp)(nil),    // 7: google.protobuf.Timestamp
}
var file_gophercourier_billing_v1_billing_proto_depIdxs = []int32{
	6, // 0: gophercourier.billing.v1.GetPaymentStatusResponse.subscription:type_name -> gophercourier.billing.v1.Subscription
	6, // 1: gophercourier.billing.v1.GetSubscriptionResponse.subscription:type_name -> gophercourier.billing.v1.Subscription
	7, // 2: gophercourier.billing.v1.Subscription.current_period_end:type_name -> google.protobuf.Timestamp
	0, // 3: gophercourier.billing.v1.BillingService.Subscribe:input_type -> gophercourier.billing.v1.SubscribeRequest
	2, // 4: gophercourier.billing.v1.BillingService.GetPaymentStatus:input_type -> gophercourier.billing.v1.GetPaymentStatusRequest
	4, // 5: gophercourier.billing.v1.BillingService.GetSubscription:input_type -> gophercourier.billing.v1.GetSubscriptionRequest
	1, // 6: gophercourier.billing.v1.BillingService.Subscribe:output_type -> gophercourier.billing.v1.SubscribeResponse
	3, // 7: gophercourier.billing.v1.BillingService.GetPaymentStatus:output_type -> gophercourier.billing.v1.GetPaymentStatusResponse
	5, // 8: gophercourier.billing.v1.BillingService.GetSubscription:output_type -> gophercourier.billing.v1.GetSubscriptionResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gophercourier_billing_v1_billing_proto_init() }
func file_gophercourier_billing_v1_billing_proto_init() {
	if File_gophercourier_billing_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophercourier_billing_v1_billing_proto_rawDesc), len(file_gophercourier_billing_v1_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophercourier_billing_v1_billing_proto_goTypes,
		DependencyIndexes: file_gophercourier_billing_v1_billing_proto_depIdxs,
		MessageInfos:      file_gophercourier_billing_v1_billing_proto_msgTypes,
	}.Build()
	File_gophercourier_billing_v1_billing_proto = out.File
	file_gophercourier_billing_v1_billing_proto_goTypes = nil
	file_gophercourier_billing_v1_billing_proto_depIdxs = nil
}
