// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gophercourier/invite/v1/invite.proto

package invitev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Invite struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id              string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_OrgId           string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3"`
	xxx_hidden_Email           string                 `protobuf:"bytes,3,opt,name=email,proto3"`
	xxx_hidden_RoleId          string                 `protobuf:"bytes,4,opt,name=role_id,json=roleId,proto3"`
	xxx_hidden_InvitedByUserId string                 `protobuf:"bytes,5,opt,name=invited_by_user_id,json=invitedByUserId,proto3"`
	xxx_hidden_MaxUses         int32                  `protobuf:"varint,6,opt,name=max_uses,json=maxUses,proto3"`
	xxx_hidden_UsedCount       int32                  `protobuf:"varint,7,opt,name=used_count,json=usedCount,proto3"`
	xxx_hidden_ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3"`
	xxx_hidden_RevokedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=revoked_at,json=revokedAt,proto3"`
	xxx_hidden_CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_Status          string                 `protobuf:"bytes,11,opt,name=status,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Invite) Reset() {
	*x = Invite{}
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invite) ProtoMessage() {}

func (x *Invite) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Invite) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Invite) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *Invite) GetEmail() string {
	if x != nil {
		return x.xxx_hidden_Email
	}
	return ""
}

func (x *Invite) GetRoleId() string {
	if x != nil {
		return x.xxx_hidden_RoleId
	}
	return ""
}

func (x *Invite) GetInvitedByUserId() string {
	if x != nil {
		return x.xxx_hidden_InvitedByUserId
	}
	return ""
}

func (x *Invite) GetMaxUses() int32 {
	if x != nil {
		return x.xxx_hidden_MaxUses
	}
	return 0
}

func (x *Invite) GetUsedCount() int32 {
	if x != nil {
		return x.xxx_hidden_UsedCount
	}
	return 0
}

func (x *Invite) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAt
	}
	return nil
}

func (x *Invite) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_RevokedAt
	}
	return nil
}

func (x *Invite) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Invite) GetStatus() string {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return ""
}

func (x *Invite) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Invite) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

func (x *Invite) SetEmail(v string) {
	x.xxx_hidden_Email = v
}

func (x *Invite) SetRoleId(v string) {
	x.xxx_hidden_RoleId = v
}

func (x *Invite) SetInvitedByUserId(v string) {
	x.xxx_hidden_InvitedByUserId = v
}

func (x *Invite) SetMaxUses(v int32) {
	x.xxx_hidden_MaxUses = v
}

func (x *Invite) SetUsedCount(v int32) {
	x.xxx_hidden_UsedCount = v
}

func (x *Invite) SetExpiresAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAt = v
}

func (x *Invite) SetRevokedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_RevokedAt = v
}

func (x *Invite) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Invite) SetStatus(v string) {
	x.xxx_hidden_Status = v
}

func (x *Invite) HasExpiresAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAt != nil
}

func (x *Invite) HasRevokedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RevokedAt != nil
}

func (x *Invite) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Invite) ClearExpiresAt() {
	x.xxx_hidden_ExpiresAt = nil
}

func (x *Invite) ClearRevokedAt() {
	x.xxx_hidden_RevokedAt = nil
}

func (x *Invite) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

type Invite_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id              string
	OrgId           string
	Email           string
	RoleId          string
	InvitedByUserId string
	MaxUses         int32
	UsedCount       int32
	ExpiresAt       *timestamppb.Timestamp
	RevokedAt       *timestamppb.Timestamp
	CreatedAt       *timestamppb.Timestamp
	Status          string
}

func (b0 Invite_builder) Build() *Invite {
	m0 := &Invite{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_OrgId = b.OrgId
	x.xxx_hidden_Email = b.Email
	x.xxx_hidden_RoleId = b.RoleId
	x.xxx_hidden_InvitedByUserId = b.InvitedByUserId
	x.xxx_hidden_MaxUses = b.MaxUses
	x.xxx_hidden_UsedCount = b.UsedCount
	x.xxx_hidden_ExpiresAt = b.ExpiresAt
	x.xxx_hidden_RevokedAt = b.RevokedAt
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_Status = b.Status
	return m0
}

type CreateInviteRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId            string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	xxx_hidden_InviteeEmail     string                 `protobuf:"bytes,2,opt,name=invitee_email,json=inviteeEmail,proto3"`
	xxx_hidden_RoleId           string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3"`
	xxx_hidden_MaxUses          int32                  `protobuf:"varint,4,opt,name=max_uses,json=maxUses,proto3"`
	xxx_hidden_ExpiresInSeconds int64                  `protobuf:"varint,5,opt,name=expires_in_seconds,json=expiresInSeconds,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CreateInviteRequest) Reset() {
	*x = CreateInviteRequest{}
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteRequest) ProtoMessage() {}

func (x *CreateInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateInviteRequest) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *CreateInviteRequest) GetInviteeEmail() string {
	if x != nil {
		return x.xxx_hidden_InviteeEmail
	}
	return ""
}

func (x *CreateInviteRequest) GetRoleId() string {
	if x != nil {
		return x.xxx_hidden_RoleId
	}
	return ""
}

func (x *CreateInviteRequest) GetMaxUses() int32 {
	if x != nil {
		return x.xxx_hidden_MaxUses
	}
	return 0
}

func (x *CreateInviteRequest) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.xxx_hidden_ExpiresInSeconds
	}
	return 0
}

func (x *CreateInviteRequest) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

func (x *CreateInviteRequest) SetInviteeEmail(v string) {
	x.xxx_hidden_InviteeEmail = v
}

func (x *CreateInviteRequest) SetRoleId(v string) {
	x.xxx_hidden_RoleId = v
}

func (x *CreateInviteRequest) SetMaxUses(v int32) {
	x.xxx_hidden_MaxUses = v
}

func (x *CreateInviteRequest) SetExpiresInSeconds(v int64) {
	x.xxx_hidden_ExpiresInSeconds = v
}

type CreateInviteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OrgId            string
	InviteeEmail     string
	RoleId           string
	MaxUses          int32
	ExpiresInSeconds int64
}

func (b0 CreateInviteRequest_builder) Build() *CreateInviteRequest {
	m0 := &CreateInviteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	x.xxx_hidden_InviteeEmail = b.InviteeEmail
	x.xxx_hidden_RoleId = b.RoleId
	x.xxx_hidden_MaxUses = b.MaxUses
	x.xxx_hidden_ExpiresInSeconds = b.ExpiresInSeconds
	return m0
}

type CreateInviteResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Invite    *Invite                `protobuf:"bytes,1,opt,name=invite,proto3"`
	xxx_hidden_Token     string                 `protobuf:"bytes,2,opt,name=token,proto3"`
	xxx_hidden_InviteUrl string                 `protobuf:"bytes,3,opt,name=invite_url,json=inviteUrl,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateInviteResponse) Reset() {
	*x = CreateInviteResponse{}
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteResponse) ProtoMessage() {}

func (x *CreateInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateInviteResponse) GetInvite() *Invite {
	if x != nil {
		return x.xxx_hidden_Invite
	}
	return nil
}

func (x *CreateInviteResponse) GetToken() string {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return ""
}

func (x *CreateInviteResponse) GetInviteUrl() string {
	if x != nil {
		return x.xxx_hidden_InviteUrl
	}
	return ""
}

func (x *CreateInviteResponse) SetInvite(v *Invite) {
	x.xxx_hidden_Invite = v
}

func (x *CreateInviteResponse) SetToken(v string) {
	x.xxx_hidden_Token = v
}

func (x *CreateInviteResponse) SetInviteUrl(v string) {
	x.xxx_hidden_InviteUrl = v
}

func (x *CreateInviteResponse) HasInvite() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Invite != nil
}

func (x *CreateInviteResponse) ClearInvite() {
	x.xxx_hidden_Invite = nil
}

type CreateInviteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Invite    *Invite
	Token     string
	InviteUrl string
}

func (b0 CreateInviteResponse_builder) Build() *CreateInviteResponse {
	m0 := &CreateInviteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Invite = b.Invite
	x.xxx_hidden_Token = b.Token
	x.xxx_hidden_InviteUrl = b.InviteUrl
	return m0
}

type RevokeInviteRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId    string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	xxx_hidden_InviteId string                 `protobuf:"bytes,2,opt,name=invite_id,json=inviteId,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RevokeInviteRequest) Reset() {
	*x = RevokeInviteRequest{}
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeInviteRequest) ProtoMessage() {}

func (x *RevokeInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RevokeInviteRequest) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *RevokeInviteRequest) GetInviteId() string {
	if x != nil {
		return x.xxx_hidden_InviteId
	}
	return ""
}

func (x *RevokeInviteRequest) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

func (x *RevokeInviteRequest) SetInviteId(v string) {
	x.xxx_hidden_InviteId = v
}

type RevokeInviteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OrgId    string
	InviteId string
}

func (b0 RevokeInviteRequest_builder) Build() *RevokeInviteRequest {
	m0 := &RevokeInviteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	x.xxx_hidden_InviteId = b.InviteId
	return m0
}

type RevokeInviteResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeInviteResponse) Reset() {
	*x = RevokeInviteResponse{}
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeInviteResponse) ProtoMessage() {}

func (x *RevokeInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RevokeInviteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RevokeInviteResponse_builder) Build() *RevokeInviteResponse {
	m0 := &RevokeInviteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListInvitesRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId  string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	xxx_hidden_Status string                 `protobuf:"bytes,2,opt,name=status,proto3"`
	xxx_hidden_Limit  int32                  `protobuf:"varint,3,opt,name=limit,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListInvitesRequest) Reset() {
	*x = ListInvitesRequest{}
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitesRequest) ProtoMessage() {}

func (x *ListInvitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListInvitesRequest) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *ListInvitesRequest) GetStatus() string {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return ""
}

func (x *ListInvitesRequest) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListInvitesRequest) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

func (x *ListInvitesRequest) SetStatus(v string) {
	x.xxx_hidden_Status = v
}

func (x *ListInvitesRequest) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
}

type ListInvitesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OrgId string
	// status filter: "" | "pending" | "expired" | "exhausted" | "revoked"
	Status string
	Limit  int32
}

func (b0 ListInvitesRequest_builder) Build() *ListInvitesRequest {
	m0 := &ListInvitesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_Limit = b.Limit
	return m0
}

type ListInvitesResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Invites *[]*Invite             `protobuf:"bytes,1,rep,name=invites,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListInvitesResponse) Reset() {
	*x = ListInvitesResponse{}
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitesResponse) ProtoMessage() {}

func (x *ListInvitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListInvitesResponse) GetInvites() []*Invite {
	if x != nil {
		if x.xxx_hidden_Invites != nil {
			return *x.xxx_hidden_Invites
		}
	}
	return nil
}

func (x *ListInvitesResponse) SetInvites(v []*Invite) {
	x.xxx_hidden_Invites = &v
}

type ListInvitesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Invites []*Invite
}

func (b0 ListInvitesResponse_builder) Build() *ListInvitesResponse {
	m0 := &ListInvitesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Invites = &b.Invites
	return m0
}

type JoinOrgRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token string                 `protobuf:"bytes,1,opt,name=token,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JoinOrgRequest) Reset() {
	*x = JoinOrgRequest{}
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinOrgRequest) ProtoMessage() {}

func (x *JoinOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JoinOrgRequest) GetToken() string {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return ""
}

func (x *JoinOrgRequest) SetToken(v string) {
	x.xxx_hidden_Token = v
}

type JoinOrgRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token string
}

func (b0 JoinOrgRequest_builder) Build() *JoinOrgRequest {
	m0 := &JoinOrgRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Token = b.Token
	return m0
}

type JoinOrgResponse struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId          string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	xxx_hidden_RoleId         string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3"`
	xxx_hidden_MembershipId   string                 `protobuf:"bytes,3,opt,name=membership_id,json=membershipId,proto3"`
	xxx_hidden_AlreadyJoined  bool                   `protobuf:"varint,4,opt,name=already_joined,json=alreadyJoined,proto3"`
	xxx_hidden_NewAccessToken string                 `protobuf:"bytes,5,opt,name=new_access_token,json=newAccessToken,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *JoinOrgResponse) Reset() {
	*x = JoinOrgResponse{}
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinOrgResponse) ProtoMessage() {}

func (x *JoinOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_invite_v1_invite_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JoinOrgResponse) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *JoinOrgResponse) GetRoleId() string {
	if x != nil {
		return x.xxx_hidden_RoleId
	}
	return ""
}

func (x *JoinOrgResponse) GetMembershipId() string {
	if x != nil {
		return x.xxx_hidden_MembershipId
	}
	return ""
}

func (x *JoinOrgResponse) GetAlreadyJoined() bool {
	if x != nil {
		return x.xxx_hidden_AlreadyJoined
	}
	return false
}

func (x *JoinOrgResponse) GetNewAccessToken() string {
	if x != nil {
		return x.xxx_hidden_NewAccessToken
	}
	return ""
}

func (x *JoinOrgResponse) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

func (x *JoinOrgResponse) SetRoleId(v string) {
	x.xxx_hidden_RoleId = v
}

func (x *JoinOrgResponse) SetMembershipId(v string) {
	x.xxx_hidden_MembershipId = v
}

func (x *JoinOrgResponse) SetAlreadyJoined(v bool) {
	x.xxx_hidden_AlreadyJoined = v
}

func (x *JoinOrgResponse) SetNewAccessToken(v string) {
	x.xxx_hidden_NewAccessToken = v
}

type JoinOrgResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OrgId         string
	RoleId        string
	MembershipId  string
	AlreadyJoined bool
	// Re-issued access token reflects the new active_org_id. Refresh token unchanged.
	NewAccessToken string
}

func (b0 JoinOrgResponse_builder) Build() *JoinOrgResponse {
	m0 := &JoinOrgResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	x.xxx_hidden_RoleId = b.RoleId
	x.xxx_hidden_MembershipId = b.MembershipId
	x.xxx_hidden_AlreadyJoined = b.AlreadyJoined
	x.xxx_hidden_NewAccessToken = b.NewAccessToken
	return m0
}

var File_gophercourier_invite_v1_invite_proto protoreflect.FileDescriptor

const file_gophercourier_invite_v1_invite_proto_rawDesc = "" +
	"\n" +
	"$gophercourier/invite/v1/invite.proto\x12\x17gophercourier.invite.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x03\n" +
	"\x06Invite\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x17\n" +
	"\arole_id\x18\x04 \x01(\tR\x06roleId\x12+\n" +
	"\x12invited_by_user_id\x18\x05 \x01(\tR\x0finvitedByUserId\x12\x19\n" +
	"\bmax_uses\x18\x06 \x01(\x05R\amaxUses\x12\x1d\n" +
	"\n" +
	"used_count\x18\a \x01(\x05R\tusedCount\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"revoked_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\"\xb3\x01\n" +
	"\x13CreateInviteRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12#\n" +
	"\rinvitee_email\x18\x02 \x01(\tR\finviteeEmail\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x19\n" +
	"\bmax_uses\x18\x04 \x01(\x05R\amaxUses\x12,\n" +
	"\x12expires_in_seconds\x18\x05 \x01(\x03R\x10expiresInSeconds\"\x84\x01\n" +
	"\x14CreateInviteResponse\x127\n" +
	"\x06invite\x18\x01 \x01(\v2\x1f.gophercourier.invite.v1.InviteR\x06invite\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"invite_url\x18\x03 \x01(\tR\tinviteUrl\"I\n" +
	"\x13RevokeInviteRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x1b\n" +
	"\tinvite_id\x18\x02 \x01(\tR\binviteId\"\x16\n" +
	"\x14RevokeInviteResponse\"Y\n" +
	"\x12ListInvitesRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"P\n" +
	"\x13ListInvitesResponse\x129\n" +
	"\ainvites\x18\x01 \x03(\v2\x1f.gophercourier.invite.v1.InviteR\ainvites\"&\n" +
	"\x0eJoinOrgRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xb7\x01\n" +
	"\x0fJoinOrgResponse\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12#\n" +
	"\rmembership_id\x18\x03 \x01(\tR\fmembershipId\x12%\n" +
	"\x0ealready_joined\x18\x04 \x01(\bR\ralreadyJoined\x12(\n" +
	"\x10new_access_token\x18\x05 \x01(\tR\x0enewAccessToken2\xb1\x03\n" +
	"\rInviteService\x12k\n" +
	"\fCreateInvite\x12,.gophercourier.invite.v1.CreateInviteRequest\x1a-.gophercourier.invite.v1.CreateInviteResponse\x12k\n" +
	"\fRevokeInvite\x12,.gophercourier.invite.v1.RevokeInviteRequest\x1a-.gophercourier.invite.v1.RevokeInviteResponse\x12h\n" +
	"\vListInvites\x12+.gophercourier.invite.v1.ListInvitesRequest\x1a,.gophercourier.invite.v1.ListInvitesResponse\x12\\\n" +
	"\aJoinOrg\x12'.gophercourier.invite.v1.JoinOrgRequest\x1a(.gophercourier.invite.v1.JoinOrgResponseB\xe9\x01\n" +
	"\x1bcom.gophercourier.invite.v1B\vInviteProtoP\x01Z?github.com/tetiva-app/proto/go/gophercourier/invite/v1;invitev1\xa2\x02\x03GIX\xaa\x02\x17Gophercourier.Invite.V1\xca\x02\x17Gophercourier\\Invite\\V1\xe2\x02#Gophercourier\\Invite\\V1\\GPBMetadata\xea\x02\x19Gophercourier::Invite::V1b\x06proto3"

var file_gophercourier_invite_v1_invite_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gophercourier_invite_v1_invite_proto_goTypes = []any{
	(*Invite)(nil),                // 0: gophercourier.invite.v1.Invite
	(*CreateInviteRequest)(nil),   // 1: gophercourier.invite.v1.CreateInviteRequest
	(*CreateInviteResponse)(nil),  // 2: gophercourier.invite.v1.CreateInviteResponse
	(*RevokeInviteRequest)(nil),   // 3: gophercourier.invite.v1.RevokeInviteRequest
	(*RevokeInviteResponse)(nil),  // 4: gophercourier.invite.v1.RevokeInviteResponse
	(*ListInvitesRequest)(nil),    // 5: gophercourier.invite.v1.ListInvitesRequest
	(*ListInvitesResponse)(nil),   // 6: gophercourier.invite.v1.ListInvitesResponse
	(*JoinOrgRequest)(nil),        // 7: gophercourier.invite.v1.JoinOrgRequest
	(*JoinOrgResponse)(nil),       // 8: gophercourier.invite.v1.JoinOrgResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_gophercourier_invite_v1_invite_proto_depIdxs = []int32{
	9, // 0: gophercourier.invite.v1.Invite.expires_at:type_name -> google.protobuf.Timestamp
	9, // 1: gophercourier.invite.v1.Invite.revoked_at:type_name -> google.protobuf.Timestamp
	9, // 2: gophercourier.invite.v1.Invite.created_at:type_name -> google.protobuf.Timestamp
	0, // 3: gophercourier.invite.v1.CreateInviteResponse.invite:type_name -> gophercourier.invite.v1.Invite
	0, // 4: gophercourier.invite.v1.ListInvitesResponse.invites:type_name -> gophercourier.invite.v1.Invite
	1, // 5: gophercourier.invite.v1.InviteService.CreateInvite:input_type -> gophercourier.invite.v1.CreateInviteRequest
	3, // 6: gophercourier.invite.v1.InviteService.RevokeInvite:input_type -> gophercourier.invite.v1.RevokeInviteRequest
	5, // 7: gophercourier.invite.v1.InviteService.ListInvites:input_type -> gophercourier.invite.v1.ListInvitesRequest
	7, // 8: gophercourier.invite.v1.InviteService.JoinOrg:input_type -> gophercourier.invite.v1.JoinOrgRequest
	2, // 9: gophercourier.invite.v1.InviteService.CreateInvite:output_type -> gophercourier.invite.v1.CreateInviteResponse
	4, // 10: gophercourier.invite.v1.InviteService.RevokeInvite:output_type -> gophercourier.invite.v1.RevokeInviteResponse
	6, // 11: gophercourier.invite.v1.InviteService.ListInvites:output_type -> gophercourier.invite.v1.ListInvitesResponse
	8, // 12: gophercourier.invite.v1.InviteService.JoinOrg:output_type -> gophercourier.invite.v1.JoinOrgResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gophercourier_invite_v1_invite_proto_init() }
func file_gophercourier_invite_v1_invite_proto_init() {
	if File_gophercourier_invite_v1_invite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophercourier_invite_v1_invite_proto_rawDesc), len(file_gophercourier_invite_v1_invite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophercourier_invite_v1_invite_proto_goTypes,
		DependencyIndexes: file_gophercourier_invite_v1_invite_proto_depIdxs,
		MessageInfos:      file_gophercourier_invite_v1_invite_proto_msgTypes,
	}.Build()
	File_gophercourier_invite_v1_invite_proto = out.File
	file_gophercourier_invite_v1_invite_proto_goTypes = nil
	file_gophercourier_invite_v1_invite_proto_depIdxs = nil
}
