// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: gophercourier/audit/v1/audit.proto

package auditv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditService_List_FullMethodName   = "/gophercourier.audit.v1.AuditService/List"
	AuditService_Export_FullMethodName = "/gophercourier.audit.v1.AuditService/Export"
)

// AuditServiceClient is the client API for AuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuditService is the read+export surface for the audit log. The writer is
// internal to the server (each mutating usecase calls audit.Logger.Log) and
// has no RPC.
//
// Per spec [06]:
//   - List/Export are gated by org:view_audit (org-scope) OR
//     platform_staff (cross-org).
//   - Cursor pagination is mandatory because audit_log is append-only and
//     grows unbounded.
//   - Export streams CSV chunks to avoid loading 100k rows into one
//     response message.
type AuditServiceClient interface {
	// List returns the next page of audit entries newest-first.
	List(ctx context.Context, in *AuditServiceListRequest, opts ...grpc.CallOption) (*AuditServiceListResponse, error)
	// Export streams CSV chunks. The first chunk includes the header row.
	// Server hard-caps at 100k rows; if more entries match, the final chunk
	// sets `truncated`.
	Export(ctx context.Context, in *AuditServiceExportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuditServiceExportResponse], error)
}

type auditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditServiceClient(cc grpc.ClientConnInterface) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) List(ctx context.Context, in *AuditServiceListRequest, opts ...grpc.CallOption) (*AuditServiceListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditServiceListResponse)
	err := c.cc.Invoke(ctx, AuditService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) Export(ctx context.Context, in *AuditServiceExportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuditServiceExportResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AuditService_ServiceDesc.Streams[0], AuditService_Export_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AuditServiceExportRequest, AuditServiceExportResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuditService_ExportClient = grpc.ServerStreamingClient[AuditServiceExportResponse]

// AuditServiceServer is the server API for AuditService service.
// All implementations must embed UnimplementedAuditServiceServer
// for forward compatibility.
//
// AuditService is the read+export surface for the audit log. The writer is
// internal to the server (each mutating usecase calls audit.Logger.Log) and
// has no RPC.
//
// Per spec [06]:
//   - List/Export are gated by org:view_audit (org-scope) OR
//     platform_staff (cross-org).
//   - Cursor pagination is mandatory because audit_log is append-only and
//     grows unbounded.
//   - Export streams CSV chunks to avoid loading 100k rows into one
//     response message.
type AuditServiceServer interface {
	// List returns the next page of audit entries newest-first.
	List(context.Context, *AuditServiceListRequest) (*AuditServiceListResponse, error)
	// Export streams CSV chunks. The first chunk includes the header row.
	// Server hard-caps at 100k rows; if more entries match, the final chunk
	// sets `truncated`.
	Export(*AuditServiceExportRequest, grpc.ServerStreamingServer[AuditServiceExportResponse]) error
	mustEmbedUnimplementedAuditServiceServer()
}

// UnimplementedAuditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditServiceServer struct{}

func (UnimplementedAuditServiceServer) List(context.Context, *AuditServiceListRequest) (*AuditServiceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAuditServiceServer) Export(*AuditServiceExportRequest, grpc.ServerStreamingServer[AuditServiceExportResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedAuditServiceServer) mustEmbedUnimplementedAuditServiceServer() {}
func (UnimplementedAuditServiceServer) testEmbeddedByValue()                      {}

// UnsafeAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditServiceServer will
// result in compilation errors.
type UnsafeAuditServiceServer interface {
	mustEmbedUnimplementedAuditServiceServer()
}

func RegisterAuditServiceServer(s grpc.ServiceRegistrar, srv AuditServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditService_ServiceDesc, srv)
}

func _AuditService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditServiceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).List(ctx, req.(*AuditServiceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_Export_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AuditServiceExportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuditServiceServer).Export(m, &grpc.GenericServerStream[AuditServiceExportRequest, AuditServiceExportResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuditService_ExportServer = grpc.ServerStreamingServer[AuditServiceExportResponse]

// AuditService_ServiceDesc is the grpc.ServiceDesc for AuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gophercourier.audit.v1.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AuditService_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Export",
			Handler:       _AuditService_Export_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gophercourier/audit/v1/audit.proto",
}
