// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gophercourier/audit/v1/audit.proto

package auditv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditServiceFilter struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId       string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3"`
	xxx_hidden_WorkspaceId string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3"`
	xxx_hidden_ActorUserId string                 `protobuf:"bytes,3,opt,name=actor_user_id,json=actorUserId,proto3"`
	xxx_hidden_Action      string                 `protobuf:"bytes,4,opt,name=action,proto3"`
	xxx_hidden_TargetId    string                 `protobuf:"bytes,5,opt,name=target_id,json=targetId,proto3"`
	xxx_hidden_From        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=from,proto3"`
	xxx_hidden_To          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=to,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuditServiceFilter) Reset() {
	*x = AuditServiceFilter{}
	mi := &file_gophercourier_audit_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditServiceFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditServiceFilter) ProtoMessage() {}

func (x *AuditServiceFilter) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_audit_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuditServiceFilter) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *AuditServiceFilter) GetWorkspaceId() string {
	if x != nil {
		return x.xxx_hidden_WorkspaceId
	}
	return ""
}

func (x *AuditServiceFilter) GetActorUserId() string {
	if x != nil {
		return x.xxx_hidden_ActorUserId
	}
	return ""
}

func (x *AuditServiceFilter) GetAction() string {
	if x != nil {
		return x.xxx_hidden_Action
	}
	return ""
}

func (x *AuditServiceFilter) GetTargetId() string {
	if x != nil {
		return x.xxx_hidden_TargetId
	}
	return ""
}

func (x *AuditServiceFilter) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_From
	}
	return nil
}

func (x *AuditServiceFilter) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_To
	}
	return nil
}

func (x *AuditServiceFilter) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

func (x *AuditServiceFilter) SetWorkspaceId(v string) {
	x.xxx_hidden_WorkspaceId = v
}

func (x *AuditServiceFilter) SetActorUserId(v string) {
	x.xxx_hidden_ActorUserId = v
}

func (x *AuditServiceFilter) SetAction(v string) {
	x.xxx_hidden_Action = v
}

func (x *AuditServiceFilter) SetTargetId(v string) {
	x.xxx_hidden_TargetId = v
}

func (x *AuditServiceFilter) SetFrom(v *timestamppb.Timestamp) {
	x.xxx_hidden_From = v
}

func (x *AuditServiceFilter) SetTo(v *timestamppb.Timestamp) {
	x.xxx_hidden_To = v
}

func (x *AuditServiceFilter) HasFrom() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_From != nil
}

func (x *AuditServiceFilter) HasTo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_To != nil
}

func (x *AuditServiceFilter) ClearFrom() {
	x.xxx_hidden_From = nil
}

func (x *AuditServiceFilter) ClearTo() {
	x.xxx_hidden_To = nil
}

type AuditServiceFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OrgId       string
	WorkspaceId string
	ActorUserId string
	Action      string
	TargetId    string
	From        *timestamppb.Timestamp
	To          *timestamppb.Timestamp
}

func (b0 AuditServiceFilter_builder) Build() *AuditServiceFilter {
	m0 := &AuditServiceFilter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OrgId = b.OrgId
	x.xxx_hidden_WorkspaceId = b.WorkspaceId
	x.xxx_hidden_ActorUserId = b.ActorUserId
	x.xxx_hidden_Action = b.Action
	x.xxx_hidden_TargetId = b.TargetId
	x.xxx_hidden_From = b.From
	x.xxx_hidden_To = b.To
	return m0
}

type AuditServiceEntry struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Timestamp      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3"`
	xxx_hidden_Action         string                 `protobuf:"bytes,2,opt,name=action,proto3"`
	xxx_hidden_ActorType      string                 `protobuf:"bytes,3,opt,name=actor_type,json=actorType,proto3"`
	xxx_hidden_ActorUserId    string                 `protobuf:"bytes,4,opt,name=actor_user_id,json=actorUserId,proto3"`
	xxx_hidden_ActorName      string                 `protobuf:"bytes,5,opt,name=actor_name,json=actorName,proto3"`
	xxx_hidden_ActorIp        string                 `protobuf:"bytes,6,opt,name=actor_ip,json=actorIp,proto3"`
	xxx_hidden_ActorUserAgent string                 `protobuf:"bytes,7,opt,name=actor_user_agent,json=actorUserAgent,proto3"`
	xxx_hidden_ActorSessionId string                 `protobuf:"bytes,8,opt,name=actor_session_id,json=actorSessionId,proto3"`
	xxx_hidden_OrgId          string                 `protobuf:"bytes,9,opt,name=org_id,json=orgId,proto3"`
	xxx_hidden_WorkspaceId    string                 `protobuf:"bytes,10,opt,name=workspace_id,json=workspaceId,proto3"`
	xxx_hidden_TargetType     string                 `protobuf:"bytes,11,opt,name=target_type,json=targetType,proto3"`
	xxx_hidden_TargetId       string                 `protobuf:"bytes,12,opt,name=target_id,json=targetId,proto3"`
	xxx_hidden_TargetName     string                 `protobuf:"bytes,13,opt,name=target_name,json=targetName,proto3"`
	xxx_hidden_MetadataJson   string                 `protobuf:"bytes,14,opt,name=metadata_json,json=metadataJson,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *AuditServiceEntry) Reset() {
	*x = AuditServiceEntry{}
	mi := &file_gophercourier_audit_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditServiceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditServiceEntry) ProtoMessage() {}

func (x *AuditServiceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_audit_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuditServiceEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *AuditServiceEntry) GetAction() string {
	if x != nil {
		return x.xxx_hidden_Action
	}
	return ""
}

func (x *AuditServiceEntry) GetActorType() string {
	if x != nil {
		return x.xxx_hidden_ActorType
	}
	return ""
}

func (x *AuditServiceEntry) GetActorUserId() string {
	if x != nil {
		return x.xxx_hidden_ActorUserId
	}
	return ""
}

func (x *AuditServiceEntry) GetActorName() string {
	if x != nil {
		return x.xxx_hidden_ActorName
	}
	return ""
}

func (x *AuditServiceEntry) GetActorIp() string {
	if x != nil {
		return x.xxx_hidden_ActorIp
	}
	return ""
}

func (x *AuditServiceEntry) GetActorUserAgent() string {
	if x != nil {
		return x.xxx_hidden_ActorUserAgent
	}
	return ""
}

func (x *AuditServiceEntry) GetActorSessionId() string {
	if x != nil {
		return x.xxx_hidden_ActorSessionId
	}
	return ""
}

func (x *AuditServiceEntry) GetOrgId() string {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return ""
}

func (x *AuditServiceEntry) GetWorkspaceId() string {
	if x != nil {
		return x.xxx_hidden_WorkspaceId
	}
	return ""
}

func (x *AuditServiceEntry) GetTargetType() string {
	if x != nil {
		return x.xxx_hidden_TargetType
	}
	return ""
}

func (x *AuditServiceEntry) GetTargetId() string {
	if x != nil {
		return x.xxx_hidden_TargetId
	}
	return ""
}

func (x *AuditServiceEntry) GetTargetName() string {
	if x != nil {
		return x.xxx_hidden_TargetName
	}
	return ""
}

func (x *AuditServiceEntry) GetMetadataJson() string {
	if x != nil {
		return x.xxx_hidden_MetadataJson
	}
	return ""
}

func (x *AuditServiceEntry) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *AuditServiceEntry) SetAction(v string) {
	x.xxx_hidden_Action = v
}

func (x *AuditServiceEntry) SetActorType(v string) {
	x.xxx_hidden_ActorType = v
}

func (x *AuditServiceEntry) SetActorUserId(v string) {
	x.xxx_hidden_ActorUserId = v
}

func (x *AuditServiceEntry) SetActorName(v string) {
	x.xxx_hidden_ActorName = v
}

func (x *AuditServiceEntry) SetActorIp(v string) {
	x.xxx_hidden_ActorIp = v
}

func (x *AuditServiceEntry) SetActorUserAgent(v string) {
	x.xxx_hidden_ActorUserAgent = v
}

func (x *AuditServiceEntry) SetActorSessionId(v string) {
	x.xxx_hidden_ActorSessionId = v
}

func (x *AuditServiceEntry) SetOrgId(v string) {
	x.xxx_hidden_OrgId = v
}

func (x *AuditServiceEntry) SetWorkspaceId(v string) {
	x.xxx_hidden_WorkspaceId = v
}

func (x *AuditServiceEntry) SetTargetType(v string) {
	x.xxx_hidden_TargetType = v
}

func (x *AuditServiceEntry) SetTargetId(v string) {
	x.xxx_hidden_TargetId = v
}

func (x *AuditServiceEntry) SetTargetName(v string) {
	x.xxx_hidden_TargetName = v
}

func (x *AuditServiceEntry) SetMetadataJson(v string) {
	x.xxx_hidden_MetadataJson = v
}

func (x *AuditServiceEntry) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *AuditServiceEntry) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

type AuditServiceEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Timestamp      *timestamppb.Timestamp
	Action         string
	ActorType      string
	ActorUserId    string
	ActorName      string
	ActorIp        string
	ActorUserAgent string
	ActorSessionId string
	OrgId          string
	WorkspaceId    string
	TargetType     string
	TargetId       string
	TargetName     string
	MetadataJson   string
}

func (b0 AuditServiceEntry_builder) Build() *AuditServiceEntry {
	m0 := &AuditServiceEntry{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Timestamp = b.Timestamp
	x.xxx_hidden_Action = b.Action
	x.xxx_hidden_ActorType = b.ActorType
	x.xxx_hidden_ActorUserId = b.ActorUserId
	x.xxx_hidden_ActorName = b.ActorName
	x.xxx_hidden_ActorIp = b.ActorIp
	x.xxx_hidden_ActorUserAgent = b.ActorUserAgent
	x.xxx_hidden_ActorSessionId = b.ActorSessionId
	x.xxx_hidden_OrgId = b.OrgId
	x.xxx_hidden_WorkspaceId = b.WorkspaceId
	x.xxx_hidden_TargetType = b.TargetType
	x.xxx_hidden_TargetId = b.TargetId
	x.xxx_hidden_TargetName = b.TargetName
	x.xxx_hidden_MetadataJson = b.MetadataJson
	return m0
}

type AuditServiceListRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filter *AuditServiceFilter    `protobuf:"bytes,1,opt,name=filter,proto3"`
	xxx_hidden_Limit  int32                  `protobuf:"varint,2,opt,name=limit,proto3"`
	xxx_hidden_Cursor string                 `protobuf:"bytes,3,opt,name=cursor,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuditServiceListRequest) Reset() {
	*x = AuditServiceListRequest{}
	mi := &file_gophercourier_audit_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditServiceListRequest) ProtoMessage() {}

func (x *AuditServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_audit_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuditServiceListRequest) GetFilter() *AuditServiceFilter {
	if x != nil {
		return x.xxx_hidden_Filter
	}
	return nil
}

func (x *AuditServiceListRequest) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *AuditServiceListRequest) GetCursor() string {
	if x != nil {
		return x.xxx_hidden_Cursor
	}
	return ""
}

func (x *AuditServiceListRequest) SetFilter(v *AuditServiceFilter) {
	x.xxx_hidden_Filter = v
}

func (x *AuditServiceListRequest) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
}

func (x *AuditServiceListRequest) SetCursor(v string) {
	x.xxx_hidden_Cursor = v
}

func (x *AuditServiceListRequest) HasFilter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Filter != nil
}

func (x *AuditServiceListRequest) ClearFilter() {
	x.xxx_hidden_Filter = nil
}

type AuditServiceListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Filter *AuditServiceFilter
	Limit  int32
	Cursor string
}

func (b0 AuditServiceListRequest_builder) Build() *AuditServiceListRequest {
	m0 := &AuditServiceListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filter = b.Filter
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Cursor = b.Cursor
	return m0
}

type AuditServiceListResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entries    *[]*AuditServiceEntry  `protobuf:"bytes,1,rep,name=entries,proto3"`
	xxx_hidden_NextCursor string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AuditServiceListResponse) Reset() {
	*x = AuditServiceListResponse{}
	mi := &file_gophercourier_audit_v1_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditServiceListResponse) ProtoMessage() {}

func (x *AuditServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_audit_v1_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuditServiceListResponse) GetEntries() []*AuditServiceEntry {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *AuditServiceListResponse) GetNextCursor() string {
	if x != nil {
		return x.xxx_hidden_NextCursor
	}
	return ""
}

func (x *AuditServiceListResponse) SetEntries(v []*AuditServiceEntry) {
	x.xxx_hidden_Entries = &v
}

func (x *AuditServiceListResponse) SetNextCursor(v string) {
	x.xxx_hidden_NextCursor = v
}

type AuditServiceListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entries    []*AuditServiceEntry
	NextCursor string
}

func (b0 AuditServiceListResponse_builder) Build() *AuditServiceListResponse {
	m0 := &AuditServiceListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	x.xxx_hidden_NextCursor = b.NextCursor
	return m0
}

type AuditServiceExportRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filter  *AuditServiceFilter    `protobuf:"bytes,1,opt,name=filter,proto3"`
	xxx_hidden_MaxRows int32                  `protobuf:"varint,2,opt,name=max_rows,json=maxRows,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AuditServiceExportRequest) Reset() {
	*x = AuditServiceExportRequest{}
	mi := &file_gophercourier_audit_v1_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditServiceExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditServiceExportRequest) ProtoMessage() {}

func (x *AuditServiceExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_audit_v1_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuditServiceExportRequest) GetFilter() *AuditServiceFilter {
	if x != nil {
		return x.xxx_hidden_Filter
	}
	return nil
}

func (x *AuditServiceExportRequest) GetMaxRows() int32 {
	if x != nil {
		return x.xxx_hidden_MaxRows
	}
	return 0
}

func (x *AuditServiceExportRequest) SetFilter(v *AuditServiceFilter) {
	x.xxx_hidden_Filter = v
}

func (x *AuditServiceExportRequest) SetMaxRows(v int32) {
	x.xxx_hidden_MaxRows = v
}

func (x *AuditServiceExportRequest) HasFilter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Filter != nil
}

func (x *AuditServiceExportRequest) ClearFilter() {
	x.xxx_hidden_Filter = nil
}

type AuditServiceExportRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Filter  *AuditServiceFilter
	MaxRows int32
}

func (b0 AuditServiceExportRequest_builder) Build() *AuditServiceExportRequest {
	m0 := &AuditServiceExportRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filter = b.Filter
	x.xxx_hidden_MaxRows = b.MaxRows
	return m0
}

type AuditServiceExportResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CsvChunk  []byte                 `protobuf:"bytes,1,opt,name=csv_chunk,json=csvChunk,proto3"`
	xxx_hidden_Last      bool                   `protobuf:"varint,2,opt,name=last,proto3"`
	xxx_hidden_Truncated bool                   `protobuf:"varint,3,opt,name=truncated,proto3"`
	xxx_hidden_RowCount  int32                  `protobuf:"varint,4,opt,name=row_count,json=rowCount,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AuditServiceExportResponse) Reset() {
	*x = AuditServiceExportResponse{}
	mi := &file_gophercourier_audit_v1_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditServiceExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditServiceExportResponse) ProtoMessage() {}

func (x *AuditServiceExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophercourier_audit_v1_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuditServiceExportResponse) GetCsvChunk() []byte {
	if x != nil {
		return x.xxx_hidden_CsvChunk
	}
	return nil
}

func (x *AuditServiceExportResponse) GetLast() bool {
	if x != nil {
		return x.xxx_hidden_Last
	}
	return false
}

func (x *AuditServiceExportResponse) GetTruncated() bool {
	if x != nil {
		return x.xxx_hidden_Truncated
	}
	return false
}

func (x *AuditServiceExportResponse) GetRowCount() int32 {
	if x != nil {
		return x.xxx_hidden_RowCount
	}
	return 0
}

func (x *AuditServiceExportResponse) SetCsvChunk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_CsvChunk = v
}

func (x *AuditServiceExportResponse) SetLast(v bool) {
	x.xxx_hidden_Last = v
}

func (x *AuditServiceExportResponse) SetTruncated(v bool) {
	x.xxx_hidden_Truncated = v
}

func (x *AuditServiceExportResponse) SetRowCount(v int32) {
	x.xxx_hidden_RowCount = v
}

type AuditServiceExportResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CsvChunk  []byte
	Last      bool
	Truncated bool
	RowCount  int32
}

func (b0 AuditServiceExportResponse_builder) Build() *AuditServiceExportResponse {
	m0 := &AuditServiceExportResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CsvChunk = b.CsvChunk
	x.xxx_hidden_Last = b.Last
	x.xxx_hidden_Truncated = b.Truncated
	x.xxx_hidden_RowCount = b.RowCount
	return m0
}

var File_gophercourier_audit_v1_audit_proto protoreflect.FileDescriptor

const file_gophercourier_audit_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\"gophercourier/audit/v1/audit.proto\x12\x16gophercourier.audit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x02\n" +
	"\x12AuditServiceFilter\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\"\n" +
	"\ractor_user_id\x18\x03 \x01(\tR\vactorUserId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1b\n" +
	"\ttarget_id\x18\x05 \x01(\tR\btargetId\x12.\n" +
	"\x04from\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"\xf4\x03\n" +
	"\x11AuditServiceEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x03 \x01(\tR\tactorType\x12\"\n" +
	"\ractor_user_id\x18\x04 \x01(\tR\vactorUserId\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x05 \x01(\tR\tactorName\x12\x19\n" +
	"\bactor_ip\x18\x06 \x01(\tR\aactorIp\x12(\n" +
	"\x10actor_user_agent\x18\a \x01(\tR\x0eactorUserAgent\x12(\n" +
	"\x10actor_session_id\x18\b \x01(\tR\x0eactorSessionId\x12\x15\n" +
	"\x06org_id\x18\t \x01(\tR\x05orgId\x12!\n" +
	"\fworkspace_id\x18\n" +
	" \x01(\tR\vworkspaceId\x12\x1f\n" +
	"\vtarget_type\x18\v \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\f \x01(\tR\btargetId\x12\x1f\n" +
	"\vtarget_name\x18\r \x01(\tR\n" +
	"targetName\x12#\n" +
	"\rmetadata_json\x18\x0e \x01(\tR\fmetadataJson\"\x8b\x01\n" +
	"\x17AuditServiceListRequest\x12B\n" +
	"\x06filter\x18\x01 \x01(\v2*.gophercourier.audit.v1.AuditServiceFilterR\x06filter\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"\x80\x01\n" +
	"\x18AuditServiceListResponse\x12C\n" +
	"\aentries\x18\x01 \x03(\v2).gophercourier.audit.v1.AuditServiceEntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"z\n" +
	"\x19AuditServiceExportRequest\x12B\n" +
	"\x06filter\x18\x01 \x01(\v2*.gophercourier.audit.v1.AuditServiceFilterR\x06filter\x12\x19\n" +
	"\bmax_rows\x18\x02 \x01(\x05R\amaxRows\"\x88\x01\n" +
	"\x1aAuditServiceExportResponse\x12\x1b\n" +
	"\tcsv_chunk\x18\x01 \x01(\fR\bcsvChunk\x12\x12\n" +
	"\x04last\x18\x02 \x01(\bR\x04last\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\x12\x1b\n" +
	"\trow_count\x18\x04 \x01(\x05R\browCount2\xec\x01\n" +
	"\fAuditService\x12i\n" +
	"\x04List\x12/.gophercourier.audit.v1.AuditServiceListRequest\x1a0.gophercourier.audit.v1.AuditServiceListResponse\x12q\n" +
	"\x06Export\x121.gophercourier.audit.v1.AuditServiceExportRequest\x1a2.gophercourier.audit.v1.AuditServiceExportResponse0\x01B\xe1\x01\n" +
	"\x1acom.gophercourier.audit.v1B\n" +
	"AuditProtoP\x01Z=github.com/tetiva-app/proto/go/gophercourier/audit/v1;auditv1\xa2\x02\x03GAX\xaa\x02\x16Gophercourier.Audit.V1\xca\x02\x16Gophercourier\\Audit\\V1\xe2\x02\"Gophercourier\\Audit\\V1\\GPBMetadata\xea\x02\x18Gophercourier::Audit::V1b\x06proto3"

var file_gophercourier_audit_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gophercourier_audit_v1_audit_proto_goTypes = []any{
	(*AuditServiceFilter)(nil),         // 0: gophercourier.audit.v1.AuditServiceFilter
	(*AuditServiceEntry)(nil),          // 1: gophercourier.audit.v1.AuditServiceEntry
	(*AuditServiceListRequest)(nil),    // 2: gophercourier.audit.v1.AuditServiceListRequest
	(*AuditServiceListResponse)(nil),   // 3: gophercourier.audit.v1.AuditServiceListResponse
	(*AuditServiceExportRequest)(nil),  // 4: gophercourier.audit.v1.AuditServiceExportRequest
	(*AuditServiceExportResponse)(nil), // 5: gophercourier.audit.v1.AuditServiceExportResponse
	(*timestamppb.Timestamp)(nil),      // 6: google.protobuf.Timestamp
}
var file_gophercourier_audit_v1_audit_proto_depIdxs = []int32{
	6, // 0: gophercourier.audit.v1.AuditServiceFilter.from:type_name -> google.protobuf.Timestamp
	6, // 1: gophercourier.audit.v1.AuditServiceFilter.to:type_name -> google.protobuf.Timestamp
	6, // 2: gophercourier.audit.v1.AuditServiceEntry.timestamp:type_name -> google.protobuf.Timestamp
	0, // 3: gophercourier.audit.v1.AuditServiceListRequest.filter:type_name -> gophercourier.audit.v1.AuditServiceFilter
	1, // 4: gophercourier.audit.v1.AuditServiceListResponse.entries:type_name -> gophercourier.audit.v1.AuditServiceEntry
	0, // 5: gophercourier.audit.v1.AuditServiceExportRequest.filter:type_name -> gophercourier.audit.v1.AuditServiceFilter
	2, // 6: gophercourier.audit.v1.AuditService.List:input_type -> gophercourier.audit.v1.AuditServiceListRequest
	4, // 7: gophercourier.audit.v1.AuditService.Export:input_type -> gophercourier.audit.v1.AuditServiceExportRequest
	3, // 8: gophercourier.audit.v1.AuditService.List:output_type -> gophercourier.audit.v1.AuditServiceListResponse
	5, // 9: gophercourier.audit.v1.AuditService.Export:output_type -> gophercourier.audit.v1.AuditServiceExportResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_gophercourier_audit_v1_audit_proto_init() }
func file_gophercourier_audit_v1_audit_proto_init() {
	if File_gophercourier_audit_v1_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophercourier_audit_v1_audit_proto_rawDesc), len(file_gophercourier_audit_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophercourier_audit_v1_audit_proto_goTypes,
		DependencyIndexes: file_gophercourier_audit_v1_audit_proto_depIdxs,
		MessageInfos:      file_gophercourier_audit_v1_audit_proto_msgTypes,
	}.Build()
	File_gophercourier_audit_v1_audit_proto = out.File
	file_gophercourier_audit_v1_audit_proto_goTypes = nil
	file_gophercourier_audit_v1_audit_proto_depIdxs = nil
}
